### ISSUE TITLE
URL shortening

### ISSUE THREAD

**Issue by cs-pchsu** [vimwiki/vimwiki#737] opened 2019-08-07 03:54 UTC
Use let g:vimwiki_url_maxsave=0 to disable shortening the URL

Will get the errors as below:

Error detected while processing function vimwiki#vars#init..<SNR>48_populate_global_variables..<SNR>48_read_global_settings_from_user:
line   59:
E706: Variable type mismatch for: users_value
line   61:
E715: Dictionary required
Vimwiki Error: The provided value '0' of the option 'g:vimwiki_diary_months' is invalid. See ':h g:vimwiki_diary_months'.
line   70:
E706: Variable type mismatch for: users_value
line   71:
E715: Dictionary required
E714: List required
Press ENTER or type command to continue

**Comment by ranebrown** [comment] 2019-08-07 11:15
I can't reproduce those errors only by setting `let g:vimwiki_url_maxsave=0`.

- What is the output of `:VimwikiShowVersion`?
- What version of Vim are you using?
- Have you tried a minimal vimrc as described [here](https://vimwiki.github.io/vimwikiwiki/Troubleshooting.html)?

**Comment by cs-pchsu** [comment] 2019-08-07 11:28
What is the output of :VimwikiShowVersion?
=> Stable version: '2.4.1'

What version of Vim are you using?
=> vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:42:52)
Included patches: 1-52
Extra patches: 8.0.0056

Have you tried a minimal vimrc as described here?
=> No error ... wow

thank you a lot

**Comment by ranebrown** [comment] 2019-08-07 11:37
> Have you tried a minimal vimrc as described here?
=> No error ... wow

If you isolate the issue in your vimrc post it here. It could help other people and I'll double check if anything can be done on the vimwiki side.

**Comment by cs-pchsu** [comment] 2019-08-07 11:49
It seems to be in conflict with other plugins, but I haven't found which plugin.

**Comment by cs-pchsu** [comment] 2019-08-07 14:33
conflict with Vundle.vim ?
https://github.com/VundleVim/Vundle.vim

only the following settings in my .vimrc

===============================================

set nocompatible              " be iMproved, required                                                                                                                                   
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vimwiki/vimwiki.git'

call vundle#end()            " required

let g:vimwiki_url_maxsave=0

===============================================

**Comment by cs-pchsu** [comment] 2019-08-08 09:50
Hi @ranebrown 

ask a question:
By the way, how to disable shortcut of <Leader>ww.

**Comment by ranebrown** [comment] 2019-08-08 11:20
Take a look at `:h g:vimwiki_map_prefix`.

Do you still see the error if you put `filetype plugin indent on    " required` after `vundle#end` accourding to the Vundle Readme that is required. Vimwiki also requires you to set:
```vim
set nocompatible
filetype plugin on
syntax on
```

**Comment by cs-pchsu** [comment] 2019-08-08 12:57
1. You put filetype plugin indent on " required after vundle#end
=> yes, also have error

2.  there are three settings as below in my vimrc.
set nocompatible
filetype plugin on
syntax on

3. put let g:vimwiki_map_prefix = '<Leader>e'，have same error previously
=>
Error detected while processing function vimwiki#vars#init..<SNR>49_populate_global_variables..<SNR>49_read_global_settings_from_user:
line   59:
E706: Variable type mismatch for: users_value
line   61:
E715: Dictionary required
Vimwiki Error: The provided value ''<Leader>e'' of the option 'g:vimwiki_diary_months' is invalid. See ':h g:vimwiki_diary_months'.
line   70:
E706: Variable type mismatch for: users_value
line   71:
E715: Dictionary required
E714: List required
Press ENTER or type command to continue

**Comment by ranebrown** [comment] 2019-08-12 11:22
Can you try the dev branch? I think this is probably related to #681 and should be fixed an that branch.

**Comment by ranebrown** [comment] 2019-08-21 03:53
I'm going to close this because I'm pretty sure it has been resolved. Reopen or comment here if you are still seeing issues.

**Closed by ranebrown** 2019-08-21 03:53 UTC

**Comment by cjue** [comment] 2019-09-26 12:16
Switching to dev fixed this for me.
