### ISSUE TITLE
Backspace from Wiki note to index not working properly on a Macbook

### ISSUE THREAD

**Issue by jonathonpday** [vimwiki/vimwiki#633] opened 2019-03-20 09:39 UTC
I am new to VIm and Vimwiki and have Vimwiki installed on two machines: a work Linux laptop and my home Macbook air.

On Linux there are no issues at all. On the Macbook though I can create a link on the wiki `.index` page and click through to a new note. However, when I try to `backspace` back to the `.index` nothing happens, until I press enter where then an error message is displayed:

`E71 error.....missing :endif`

I am then prompted to press `Enter` and return to the `.index`. 

However, when I use the diary element on my Macbook `backspace` works fine and I can easily move between diary entries and `diary.index` with no errors.

Could someone advise how best to resolve this?

**Comment by ranebrown** [comment] 2019-03-20 12:39
I haven't seen this issue on a mac myself.

1. Are you using the default syntax?
2. Can you post your `.vimrc` or at least the vimwiki settings?
3. Are there any additional error messages or more information such as a line number where the error originates?

**Comment by jonathonpday** [comment] 2019-03-20 17:06
My Apologies, to answer your questions:

1. As far as I am aware yes, I am using the default syntax (.wiki) and I have not touched the source code as I do not yet know vimscript.

2. My vimrc contains the following:

`set number`
`syntax on`
`set tabstop=2`
`set softtabstop=2`
`set expandtab`
`set cursorline`
`set showmatch`
`set wildmenu`
`colorscheme slate`
`filetype indent on`
`filetype plugin on`
`set nocompatible`
`set backspace=indent,eol,start`
`let g:vimwiki_list = [{'path': '$HOME/Dropbox/vimwiki'}]`

3. The full error message I receive when I first try to `backspace` and then press `enter` is:
`Error detected while processing function vimwiki#base#go_back_link[4]..vimwiki#b
ase#edit_file:`
`line   21:`
`E325: ATTENTION`
`Error detected while processing function vimwiki#base#go_back_link:`
`line    4:`
`E171: Missing :endif`
`Press ENTER or type command to continue`

Please let me know if you need anything else.

**Comment by hq6** [comment] 2019-03-20 18:20
How did you install vimwiki? 

If it was through `git clone`, please give the commit hash as well as the output of `git diff` in the source directory.

If it was through some other mechanism, please open the file `vimwiki/autoload/vimwiki/base.vim` and copy out the full body of the function `vimwiki#base#go_back_link` to this Issue.

**Comment by ranebrown** [comment] 2019-03-20 18:40
@hq6 It looks like you are interested in taking this over (which is fine by me). We have plenty of open issues so it doesn't make sense for more than one of us to work on the same one.

**Comment by hq6** [comment] 2019-03-20 18:52
@ranebrown That's a fair point, and I'll try to find new issues in the future to avoid causing you to context switch. 

My previous modus operandi was to try to provide input wherever I saw an opportunity to be helpful, but I agree that it's probably more efficient (at least until we clear this backlog) if only one of us is looking at each issue.

I will take over this issue to avoid you needing to context switch further on this, and try to stick to new issues in the future. :)

**Comment by jonathonpday** [comment] 2019-03-20 18:57
@hq6 Thanks for the suggestion, I did git cline but I am afraid I dont know what you mean by the commit hash - a quick google was not helpful but I will keep looking.

the `git diff` resulted in:
`diff --git a/vimrc b/vimrc`
`index 6b60a3f..48b1eeb 100644`
`--- a/vimrc`
`+++ b/vimrc`
`@@ -9,4 +9,5 @@ set wildmenu`
` colorscheme slate`
 `filetype indent on`
 filetype plugin on`
`-`
`+set nocompatible`
`+let g:vimwiki_list = [{'path': '$HOME/Dropbox/vimwiki'}]`
`(END)`

will keep looking on the has, or is there an alternative?

**Comment by jonathonpday** [comment] 2019-03-20 19:00
found it I think!

commit hash is:

dc011a65fd526df1dc1284f7b3ebf7fcbf593db7

hope that helps!

**Comment by hq6** [comment] 2019-03-20 20:07
@jonathonpday , I think you might not be in the `vimwiki` source repository, since the commit hash you provided does not exist in the public Vimwiki repository. 

Please try running the following commands and copy the output here.

```
cd ~/.vim/pack/plugins/start/vimwiki
git branch
git log
git diff
```

**Comment by jonathonpday** [comment] 2019-03-20 20:30
@hq6 

git branch:

`* master`

git log:

commit 605604fc23e5717dd7063c1b7265c3d6c7b7ed0a (HEAD -> master, origin/master, origin/HEAD)
Author: Rane Brown <ranebrown@users.noreply.github.com>
Date:   Sun Mar 17 22:24:51 2019 -0600

    Create an issue template

commit 7f98bfbe4bb887edde1c88335138591f81d87be5
Author: Rane Brown <ranebrown@users.noreply.github.com>
Date:   Sun Mar 17 22:06:10 2019 -0600

    Create a pull request template.

commit 5ab8f8672e6832da8f5a7eb371d2b24e8e0fff2c
Author: Michael F. Schönitzer <michael@schoenitzer.de>
Date:   Sat Mar 9 14:49:01 2019 +0100

    Add call for help and note about Riot

commit 417490f30b3aaec600c19cfa59018cf2368dd87b
Author: Stefan Huber <shuber@sthu.org>
Date:   Tue Jan 29 19:45:46 2019 +0100

    doc: Fix spelling for <Leader>

commit 4e6db92d2c5a3ff24e64f6ba88220e7000f6c2b3
Author: Nico <nicolasbrailo@gmail.com>
Date:   Sat Dec 15 11:33:38 2018 +0100

    Patch for issue #585 - implement suggested improvements

commit aca8c2b8cc721319fcd41ffb7f5ae3b92b8070a1
Author: Nicolas Brailovsky <brailovs@nl1lxl-105201.ttg.global>
Date:   Wed Dec 12 18:07:30 2018 +0100

    Patch for issue #585, fix anchor links for multiple extensions

commit 7ffc295094debc3d521cecf267d736cc8562c20e
Author: CUI Hao (Lab) <cuihao.leo@gmail.com>
Date:   Mon Oct 8 23:12:57 2018 +0800

    Update Chinese readme & add links to each readme

commit f882cf01528e471d78d10df28ce407bc1cc23bc9
Author: Fredrik Arnerup <fredrik.arnerup@rte.se>
Date:   Mon Sep 17 11:21:07 2018 +0200

    Don't include trailing period in link

commit f55ec31675e372e2f59d51322b445ea91191ec2b
Author: Daniel Quomsieh <DQuomsieh@gmail.com>
Date:   Fri Aug 31 16:05:42 2018 +0300

    fixed writing error

commit 9f797f6ad9fd2a5e943bc99b5f9cd44b2cbd0fb4
Author: Steven Stallion <sstallion@gmail.com>
Date:   Thu Jul 12 11:11:05 2018 -0500

git log: blank - nothing shown.

Cheers again.

**Comment by hq6** [comment] 2019-03-20 20:54
If `git` does not detect a difference, the only thing I can think of is that somehow the line endings are incorrect and that's eating up the `endif`. This is a long shot, but can you run the following commands and copy the output?
```
cd ~/.vim/pack/plugins/start/vimwiki
grep -A55 -r 'function! vimwiki#base#edit_file'
```

**Comment by jonathonpday** [comment] 2019-03-20 21:43
@hq6 

both grep commands return the same output:

`grep: warning: recursive search of stdin`

No other output seen at the moment.

**Comment by hq6** [comment] 2019-03-20 21:46
@jonathonpday Sorry, please see the edited commands.

**Comment by jonathonpday** [comment] 2019-03-20 22:07
@hq6 Sorry, I cannot see any edits to the commands, I ran the ones above again just in case but the result (recursive search of STDIN) was the same.

**Comment by hq6** [comment] 2019-03-20 22:08
@jonathonpday I added `*` to the end of the `grep` command.

**Comment by jonathonpday** [comment] 2019-03-20 22:16
@hq6 Sorry did not go through it has now!

grep -A55 -r 'function! vimwiki#base#edit_file' *

output is:

autoload/vimwiki/base.vim:function! vimwiki#base#edit_file(command, filename, anchor, ...)
autoload/vimwiki/base.vim-  let fname = escape(a:filename, '% *|#`')
autoload/vimwiki/base.vim-  let dir = fnamemodify(a:filename, ":p:h")
autoload/vimwiki/base.vim-
autoload/vimwiki/base.vim-  let ok = vimwiki#path#mkdir(dir, 1)
autoload/vimwiki/base.vim-
autoload/vimwiki/base.vim-  if !ok
autoload/vimwiki/base.vim-    echomsg ' '
autoload/vimwiki/base.vim-    echomsg 'Vimwiki Error: Unable to edit file in non-existent directory: '.dir
autoload/vimwiki/base.vim-    return
autoload/vimwiki/base.vim-  endif
autoload/vimwiki/base.vim-
autoload/vimwiki/base.vim-  " Check if the file we want to open is already the current file
autoload/vimwiki/base.vim-  " which happens if we jump to an achor in the current file.
autoload/vimwiki/base.vim-  " This hack is necessary because apparently Vim messes up the result of
autoload/vimwiki/base.vim-  " getpos() directly after this command. Strange.
autoload/vimwiki/base.vim-  if !(a:command ==# ':e ' && vimwiki#path#is_equal(a:filename, expand('%:p')))
autoload/vimwiki/base.vim-    try
autoload/vimwiki/base.vim-      if &autowriteall && !&hidden  " in this case, the file is saved before switching to the
autoload/vimwiki/base.vim-        " new buffer. This causes Vim to show two messages in the command line which triggers
autoload/vimwiki/base.vim-        " the annoying hit-enter prompt. Solution: show no messages at all.
autoload/vimwiki/base.vim-        silent execute a:command fname
autoload/vimwiki/base.vim-      else
autoload/vimwiki/base.vim-        execute a:command fname
autoload/vimwiki/base.vim-      endif
autoload/vimwiki/base.vim-    catch /E37:/
autoload/vimwiki/base.vim-      echomsg 'Vimwiki: The current file is modified. Hint: Take a look at'
autoload/vimwiki/base.vim-            \ ''':h g:vimwiki_autowriteall'' to see how to save automatically.'
autoload/vimwiki/base.vim-      return
autoload/vimwiki/base.vim-    endtry
autoload/vimwiki/base.vim-
autoload/vimwiki/base.vim-    " If the opened file was not already loaded by Vim, an autocommand is
autoload/vimwiki/base.vim-    " triggered at this point
autoload/vimwiki/base.vim-
autoload/vimwiki/base.vim-    " Make sure no other plugin takes ownership over the new file. Vimwiki
autoload/vimwiki/base.vim-    " rules them all! Well, except for directories, which may be opened with
autoload/vimwiki/base.vim-    " Netrw
autoload/vimwiki/base.vim-    if &filetype != 'vimwiki' && fname !~ '\m/$'
autoload/vimwiki/base.vim-      setfiletype vimwiki
autoload/vimwiki/base.vim-    endif
autoload/vimwiki/base.vim-  endif
autoload/vimwiki/base.vim-  if a:anchor != ''
autoload/vimwiki/base.vim-    call s:jump_to_anchor(a:anchor)
autoload/vimwiki/base.vim-  endif
autoload/vimwiki/base.vim-
autoload/vimwiki/base.vim-  " save previous link
autoload/vimwiki/base.vim-  " a:1 -- previous vimwiki link to save
autoload/vimwiki/base.vim-  " a:2 -- should we update previous link
autoload/vimwiki/base.vim-  if a:0 && a:2 && len(a:1) > 0
autoload/vimwiki/base.vim-    call vimwiki#vars#set_bufferlocal('prev_link', a:1)
autoload/vimwiki/base.vim-  endif
autoload/vimwiki/base.vim-endfunction
autoload/vimwiki/base.vim-
autoload/vimwiki/base.vim-
autoload/vimwiki/base.vim-function! vimwiki#base#search_word(wikiRx, cmd)
autoload/vimwiki/base.vim-  let match_line = search(a:wikiRx, 's'.a:cmd)

**Comment by jonathonpday** [comment] 2019-03-20 22:17
@hq6 

grep -A55 -r 'function! vimwiki#base#edit_file' * | xxd

output is:

00000000: 6175 746f 6c6f 6164 2f76 696d 7769 6b69  autoload/vimwiki
00000010: 2f62 6173 652e 7669 6d3a 6675 6e63 7469  /base.vim:functi
00000020: 6f6e 2120 7669 6d77 696b 6923 6261 7365  on! vimwiki#base
00000030: 2365 6469 745f 6669 6c65 2863 6f6d 6d61  #edit_file(comma
00000040: 6e64 2c20 6669 6c65 6e61 6d65 2c20 616e  nd, filename, an
00000050: 6368 6f72 2c20 2e2e 2e29 0a61 7574 6f6c  chor, ...).autol
00000060: 6f61 642f 7669 6d77 696b 692f 6261 7365  oad/vimwiki/base
00000070: 2e76 696d 2d20 206c 6574 2066 6e61 6d65  .vim-  let fname
00000080: 203d 2065 7363 6170 6528 613a 6669 6c65   = escape(a:file
00000090: 6e61 6d65 2c20 2725 202a 7c23 6027 290a  name, '% *|#`').
000000a0: 6175 746f 6c6f 6164 2f76 696d 7769 6b69  autoload/vimwiki
000000b0: 2f62 6173 652e 7669 6d2d 2020 6c65 7420  /base.vim-  let
000000c0: 6469 7220 3d20 666e 616d 656d 6f64 6966  dir = fnamemodif
000000d0: 7928 613a 6669 6c65 6e61 6d65 2c20 223a  y(a:filename, ":
000000e0: 703a 6822 290a 6175 746f 6c6f 6164 2f76  p:h").autoload/v
000000f0: 696d 7769 6b69 2f62 6173 652e 7669 6d2d  imwiki/base.vim-
00000100: 0a61 7574 6f6c 6f61 642f 7669 6d77 696b  .autoload/vimwik
00000110: 692f 6261 7365 2e76 696d 2d20 206c 6574  i/base.vim-  let
00000120: 206f 6b20 3d20 7669 6d77 696b 6923 7061   ok = vimwiki#pa
00000130: 7468 236d 6b64 6972 2864 6972 2c20 3129  th#mkdir(dir, 1)
00000140: 0a61 7574 6f6c 6f61 642f 7669 6d77 696b  .autoload/vimwik
00000150: 692f 6261 7365 2e76 696d 2d0a 6175 746f  i/base.vim-.auto
00000160: 6c6f 6164 2f76 696d 7769 6b69 2f62 6173  load/vimwiki/bas
00000170: 652e 7669 6d2d 2020 6966 2021 6f6b 0a61  e.vim-  if !ok.a
00000180: 7574 6f6c 6f61 642f 7669 6d77 696b 692f  utoload/vimwiki/
00000190: 6261 7365 2e76 696d 2d20 2020 2065 6368  base.vim-    ech
000001a0: 6f6d 7367 2027 2027 0a61 7574 6f6c 6f61  omsg ' '.autoloa
000001b0: 642f 7669 6d77 696b 692f 6261 7365 2e76  d/vimwiki/base.v
000001c0: 696d 2d20 2020 2065 6368 6f6d 7367 2027  im-    echomsg '
000001d0: 5669 6d77 696b 6920 4572 726f 723a 2055  Vimwiki Error: U
000001e0: 6e61 626c 6520 746f 2065 6469 7420 6669  nable to edit fi
000001f0: 6c65 2069 6e20 6e6f 6e2d 6578 6973 7465  le in non-existe
00000200: 6e74 2064 6972 6563 746f 7279 3a20 272e  nt directory: '.
00000210: 6469 720a 6175 746f 6c6f 6164 2f76 696d  dir.autoload/vim
00000220: 7769 6b69 2f62 6173 652e 7669 6d2d 2020  wiki/base.vim-
00000230: 2020 7265 7475 726e 0a61 7574 6f6c 6f61    return.autoloa
00000240: 642f 7669 6d77 696b 692f 6261 7365 2e76  d/vimwiki/base.v
00000250: 696d 2d20 2065 6e64 6966 0a61 7574 6f6c  im-  endif.autol
00000260: 6f61 642f 7669 6d77 696b 692f 6261 7365  oad/vimwiki/base
00000270: 2e76 696d 2d0a 6175 746f 6c6f 6164 2f76  .vim-.autoload/v
00000280: 696d 7769 6b69 2f62 6173 652e 7669 6d2d  imwiki/base.vim-
00000290: 2020 2220 4368 6563 6b20 6966 2074 6865    " Check if the
000002a0: 2066 696c 6520 7765 2077 616e 7420 746f   file we want to
000002b0: 206f 7065 6e20 6973 2061 6c72 6561 6479   open is already
000002c0: 2074 6865 2063 7572 7265 6e74 2066 696c   the current fil
000002d0: 650a 6175 746f 6c6f 6164 2f76 696d 7769  e.autoload/vimwi
000002e0: 6b69 2f62 6173 652e 7669 6d2d 2020 2220  ki/base.vim-  "
000002f0: 7768 6963 6820 6861 7070 656e 7320 6966  which happens if
00000300: 2077 6520 6a75 6d70 2074 6f20 616e 2061   we jump to an a
00000310: 6368 6f72 2069 6e20 7468 6520 6375 7272  chor in the curr
00000320: 656e 7420 6669 6c65 2e0a 6175 746f 6c6f  ent file..autolo
00000330: 6164 2f76 696d 7769 6b69 2f62 6173 652e  ad/vimwiki/base.
00000340: 7669 6d2d 2020 2220 5468 6973 2068 6163  vim-  " This hac
00000350: 6b20 6973 206e 6563 6573 7361 7279 2062  k is necessary b
00000360: 6563 6175 7365 2061 7070 6172 656e 746c  ecause apparentl
00000370: 7920 5669 6d20 6d65 7373 6573 2075 7020  y Vim messes up
00000380: 7468 6520 7265 7375 6c74 206f 660a 6175  the result of.au
00000390: 746f 6c6f 6164 2f76 696d 7769 6b69 2f62  toload/vimwiki/b
000003a0: 6173 652e 7669 6d2d 2020 2220 6765 7470  ase.vim-  " getp
000003b0: 6f73 2829 2064 6972 6563 746c 7920 6166  os() directly af
000003c0: 7465 7220 7468 6973 2063 6f6d 6d61 6e64  ter this command
000003d0: 2e20 5374 7261 6e67 652e 0a61 7574 6f6c  . Strange..autol
000003e0: 6f61 642f 7669 6d77 696b 692f 6261 7365  oad/vimwiki/base
000003f0: 2e76 696d 2d20 2069 6620 2128 613a 636f  .vim-  if !(a:co
00000400: 6d6d 616e 6420 3d3d 2320 273a 6520 2720  mmand ==# ':e '
00000410: 2626 2076 696d 7769 6b69 2370 6174 6823  && vimwiki#path#
00000420: 6973 5f65 7175 616c 2861 3a66 696c 656e  is_equal(a:filen
00000430: 616d 652c 2065 7870 616e 6428 2725 3a70  ame, expand('%:p
00000440: 2729 2929 0a61 7574 6f6c 6f61 642f 7669  '))).autoload/vi
00000450: 6d77 696b 692f 6261 7365 2e76 696d 2d20  mwiki/base.vim-
00000460: 2020 2074 7279 0a61 7574 6f6c 6f61 642f     try.autoload/
00000470: 7669 6d77 696b 692f 6261 7365 2e76 696d  vimwiki/base.vim
00000480: 2d20 2020 2020 2069 6620 2661 7574 6f77  -      if &autow
00000490: 7269 7465 616c 6c20 2626 2021 2668 6964  riteall && !&hid
000004a0: 6465 6e20 2022 2069 6e20 7468 6973 2063  den  " in this c
000004b0: 6173 652c 2074 6865 2066 696c 6520 6973  ase, the file is
000004c0: 2073 6176 6564 2062 6566 6f72 6520 7377   saved before sw
000004d0: 6974 6368 696e 6720 746f 2074 6865 0a61  itching to the.a
000004e0: 7574 6f6c 6f61 642f 7669 6d77 696b 692f  utoload/vimwiki/
000004f0: 6261 7365 2e76 696d 2d20 2020 2020 2020  base.vim-
00000500: 2022 206e 6577 2062 7566 6665 722e 2054   " new buffer. T
00000510: 6869 7320 6361 7573 6573 2056 696d 2074  his causes Vim t
00000520: 6f20 7368 6f77 2074 776f 206d 6573 7361  o show two messa
00000530: 6765 7320 696e 2074 6865 2063 6f6d 6d61  ges in the comma
00000540: 6e64 206c 696e 6520 7768 6963 6820 7472  nd line which tr
00000550: 6967 6765 7273 0a61 7574 6f6c 6f61 642f  iggers.autoload/
00000560: 7669 6d77 696b 692f 6261 7365 2e76 696d  vimwiki/base.vim
00000570: 2d20 2020 2020 2020 2022 2074 6865 2061  -        " the a
00000580: 6e6e 6f79 696e 6720 6869 742d 656e 7465  nnoying hit-ente
00000590: 7220 7072 6f6d 7074 2e20 536f 6c75 7469  r prompt. Soluti
000005a0: 6f6e 3a20 7368 6f77 206e 6f20 6d65 7373  on: show no mess
000005b0: 6167 6573 2061 7420 616c 6c2e 0a61 7574  ages at all..aut
000005c0: 6f6c 6f61 642f 7669 6d77 696b 692f 6261  oload/vimwiki/ba
000005d0: 7365 2e76 696d 2d20 2020 2020 2020 2073  se.vim-        s
000005e0: 696c 656e 7420 6578 6563 7574 6520 613a  ilent execute a:
000005f0: 636f 6d6d 616e 6420 666e 616d 650a 6175  command fname.au
00000600: 746f 6c6f 6164 2f76 696d 7769 6b69 2f62  toload/vimwiki/b
00000610: 6173 652e 7669 6d2d 2020 2020 2020 656c  ase.vim-      el
00000620: 7365 0a61 7574 6f6c 6f61 642f 7669 6d77  se.autoload/vimw
00000630: 696b 692f 6261 7365 2e76 696d 2d20 2020  iki/base.vim-
00000640: 2020 2020 2065 7865 6375 7465 2061 3a63       execute a:c
00000650: 6f6d 6d61 6e64 2066 6e61 6d65 0a61 7574  ommand fname.aut
00000660: 6f6c 6f61 642f 7669 6d77 696b 692f 6261  oload/vimwiki/ba
00000670: 7365 2e76 696d 2d20 2020 2020 2065 6e64  se.vim-      end
00000680: 6966 0a61 7574 6f6c 6f61 642f 7669 6d77  if.autoload/vimw
00000690: 696b 692f 6261 7365 2e76 696d 2d20 2020  iki/base.vim-
000006a0: 2063 6174 6368 202f 4533 373a 2f0a 6175   catch /E37:/.au
000006b0: 746f 6c6f 6164 2f76 696d 7769 6b69 2f62  toload/vimwiki/b
000006c0: 6173 652e 7669 6d2d 2020 2020 2020 6563  ase.vim-      ec
000006d0: 686f 6d73 6720 2756 696d 7769 6b69 3a20  homsg 'Vimwiki:
000006e0: 5468 6520 6375 7272 656e 7420 6669 6c65  The current file
000006f0: 2069 7320 6d6f 6469 6669 6564 2e20 4869   is modified. Hi
00000700: 6e74 3a20 5461 6b65 2061 206c 6f6f 6b20  nt: Take a look
00000710: 6174 270a 6175 746f 6c6f 6164 2f76 696d  at'.autoload/vim
00000720: 7769 6b69 2f62 6173 652e 7669 6d2d 2020  wiki/base.vim-
00000730: 2020 2020 2020 2020 2020 5c20 2727 273a            \ ''':
00000740: 6820 673a 7669 6d77 696b 695f 6175 746f  h g:vimwiki_auto
00000750: 7772 6974 6561 6c6c 2727 2074 6f20 7365  writeall'' to se
00000760: 6520 686f 7720 746f 2073 6176 6520 6175  e how to save au
00000770: 746f 6d61 7469 6361 6c6c 792e 270a 6175  tomatically.'.au
00000780: 746f 6c6f 6164 2f76 696d 7769 6b69 2f62  toload/vimwiki/b
00000790: 6173 652e 7669 6d2d 2020 2020 2020 7265  ase.vim-      re
000007a0: 7475 726e 0a61 7574 6f6c 6f61 642f 7669  turn.autoload/vi
000007b0: 6d77 696b 692f 6261 7365 2e76 696d 2d20  mwiki/base.vim-
000007c0: 2020 2065 6e64 7472 790a 6175 746f 6c6f     endtry.autolo
000007d0: 6164 2f76 696d 7769 6b69 2f62 6173 652e  ad/vimwiki/base.
000007e0: 7669 6d2d 0a61 7574 6f6c 6f61 642f 7669  vim-.autoload/vi
000007f0: 6d77 696b 692f 6261 7365 2e76 696d 2d20  mwiki/base.vim-
00000800: 2020 2022 2049 6620 7468 6520 6f70 656e     " If the open
00000810: 6564 2066 696c 6520 7761 7320 6e6f 7420  ed file was not
00000820: 616c 7265 6164 7920 6c6f 6164 6564 2062  already loaded b
00000830: 7920 5669 6d2c 2061 6e20 6175 746f 636f  y Vim, an autoco
00000840: 6d6d 616e 6420 6973 0a61 7574 6f6c 6f61  mmand is.autoloa
00000850: 642f 7669 6d77 696b 692f 6261 7365 2e76  d/vimwiki/base.v
00000860: 696d 2d20 2020 2022 2074 7269 6767 6572  im-    " trigger
00000870: 6564 2061 7420 7468 6973 2070 6f69 6e74  ed at this point
00000880: 0a61 7574 6f6c 6f61 642f 7669 6d77 696b  .autoload/vimwik
00000890: 692f 6261 7365 2e76 696d 2d0a 6175 746f  i/base.vim-.auto
000008a0: 6c6f 6164 2f76 696d 7769 6b69 2f62 6173  load/vimwiki/bas
000008b0: 652e 7669 6d2d 2020 2020 2220 4d61 6b65  e.vim-    " Make
000008c0: 2073 7572 6520 6e6f 206f 7468 6572 2070   sure no other p
000008d0: 6c75 6769 6e20 7461 6b65 7320 6f77 6e65  lugin takes owne
000008e0: 7273 6869 7020 6f76 6572 2074 6865 206e  rship over the n
000008f0: 6577 2066 696c 652e 2056 696d 7769 6b69  ew file. Vimwiki
00000900: 0a61 7574 6f6c 6f61 642f 7669 6d77 696b  .autoload/vimwik
00000910: 692f 6261 7365 2e76 696d 2d20 2020 2022  i/base.vim-    "
00000920: 2072 756c 6573 2074 6865 6d20 616c 6c21   rules them all!
00000930: 2057 656c 6c2c 2065 7863 6570 7420 666f   Well, except fo
00000940: 7220 6469 7265 6374 6f72 6965 732c 2077  r directories, w
00000950: 6869 6368 206d 6179 2062 6520 6f70 656e  hich may be open
00000960: 6564 2077 6974 680a 6175 746f 6c6f 6164  ed with.autoload
00000970: 2f76 696d 7769 6b69 2f62 6173 652e 7669  /vimwiki/base.vi
00000980: 6d2d 2020 2020 2220 4e65 7472 770a 6175  m-    " Netrw.au
00000990: 746f 6c6f 6164 2f76 696d 7769 6b69 2f62  toload/vimwiki/b
000009a0: 6173 652e 7669 6d2d 2020 2020 6966 2026  ase.vim-    if &
000009b0: 6669 6c65 7479 7065 2021 3d20 2776 696d  filetype != 'vim
000009c0: 7769 6b69 2720 2626 2066 6e61 6d65 2021  wiki' && fname !
000009d0: 7e20 275c 6d2f 2427 0a61 7574 6f6c 6f61  ~ '\m/$'.autoloa
000009e0: 642f 7669 6d77 696b 692f 6261 7365 2e76  d/vimwiki/base.v
000009f0: 696d 2d20 2020 2020 2073 6574 6669 6c65  im-      setfile
00000a00: 7479 7065 2076 696d 7769 6b69 0a61 7574  type vimwiki.aut
00000a10: 6f6c 6f61 642f 7669 6d77 696b 692f 6261  oload/vimwiki/ba
00000a20: 7365 2e76 696d 2d20 2020 2065 6e64 6966  se.vim-    endif
00000a30: 0a61 7574 6f6c 6f61 642f 7669 6d77 696b  .autoload/vimwik
00000a40: 692f 6261 7365 2e76 696d 2d20 2065 6e64  i/base.vim-  end
00000a50: 6966 0a61 7574 6f6c 6f61 642f 7669 6d77  if.autoload/vimw
00000a60: 696b 692f 6261 7365 2e76 696d 2d20 2069  iki/base.vim-  i
00000a70: 6620 613a 616e 6368 6f72 2021 3d20 2727  f a:anchor != ''
00000a80: 0a61 7574 6f6c 6f61 642f 7669 6d77 696b  .autoload/vimwik
00000a90: 692f 6261 7365 2e76 696d 2d20 2020 2063  i/base.vim-    c
00000aa0: 616c 6c20 733a 6a75 6d70 5f74 6f5f 616e  all s:jump_to_an
00000ab0: 6368 6f72 2861 3a61 6e63 686f 7229 0a61  chor(a:anchor).a
00000ac0: 7574 6f6c 6f61 642f 7669 6d77 696b 692f  utoload/vimwiki/
00000ad0: 6261 7365 2e76 696d 2d20 2065 6e64 6966  base.vim-  endif
00000ae0: 0a61 7574 6f6c 6f61 642f 7669 6d77 696b  .autoload/vimwik
00000af0: 692f 6261 7365 2e76 696d 2d0a 6175 746f  i/base.vim-.auto
00000b00: 6c6f 6164 2f76 696d 7769 6b69 2f62 6173  load/vimwiki/bas
00000b10: 652e 7669 6d2d 2020 2220 7361 7665 2070  e.vim-  " save p
00000b20: 7265 7669 6f75 7320 6c69 6e6b 0a61 7574  revious link.aut
00000b30: 6f6c 6f61 642f 7669 6d77 696b 692f 6261  oload/vimwiki/ba
00000b40: 7365 2e76 696d 2d20 2022 2061 3a31 202d  se.vim-  " a:1 -
00000b50: 2d20 7072 6576 696f 7573 2076 696d 7769  - previous vimwi
00000b60: 6b69 206c 696e 6b20 746f 2073 6176 650a  ki link to save.
00000b70: 6175 746f 6c6f 6164 2f76 696d 7769 6b69  autoload/vimwiki
00000b80: 2f62 6173 652e 7669 6d2d 2020 2220 613a  /base.vim-  " a:
00000b90: 3220 2d2d 2073 686f 756c 6420 7765 2075  2 -- should we u
00000ba0: 7064 6174 6520 7072 6576 696f 7573 206c  pdate previous l
00000bb0: 696e 6b0a 6175 746f 6c6f 6164 2f76 696d  ink.autoload/vim
00000bc0: 7769 6b69 2f62 6173 652e 7669 6d2d 2020  wiki/base.vim-
00000bd0: 6966 2061 3a30 2026 2620 613a 3220 2626  if a:0 && a:2 &&
00000be0: 206c 656e 2861 3a31 2920 3e20 300a 6175   len(a:1) > 0.au
00000bf0: 746f 6c6f 6164 2f76 696d 7769 6b69 2f62  toload/vimwiki/b
00000c00: 6173 652e 7669 6d2d 2020 2020 6361 6c6c  ase.vim-    call
00000c10: 2076 696d 7769 6b69 2376 6172 7323 7365   vimwiki#vars#se
00000c20: 745f 6275 6666 6572 6c6f 6361 6c28 2770  t_bufferlocal('p
00000c30: 7265 765f 6c69 6e6b 272c 2061 3a31 290a  rev_link', a:1).
00000c40: 6175 746f 6c6f 6164 2f76 696d 7769 6b69  autoload/vimwiki
00000c50: 2f62 6173 652e 7669 6d2d 2020 656e 6469  /base.vim-  endi
00000c60: 660a 6175 746f 6c6f 6164 2f76 696d 7769  f.autoload/vimwi
00000c70: 6b69 2f62 6173 652e 7669 6d2d 656e 6466  ki/base.vim-endf
00000c80: 756e 6374 696f 6e0a 6175 746f 6c6f 6164  unction.autoload
00000c90: 2f76 696d 7769 6b69 2f62 6173 652e 7669  /vimwiki/base.vi
00000ca0: 6d2d 0a61 7574 6f6c 6f61 642f 7669 6d77  m-.autoload/vimw
00000cb0: 696b 692f 6261 7365 2e76 696d 2d0a 6175  iki/base.vim-.au
00000cc0: 746f 6c6f 6164 2f76 696d 7769 6b69 2f62  toload/vimwiki/b
00000cd0: 6173 652e 7669 6d2d 6675 6e63 7469 6f6e  ase.vim-function
00000ce0: 2120 7669 6d77 696b 6923 6261 7365 2373  ! vimwiki#base#s
00000cf0: 6561 7263 685f 776f 7264 2877 696b 6952  earch_word(wikiR
00000d00: 782c 2063 6d64 290a 6175 746f 6c6f 6164  x, cmd).autoload
00000d10: 2f76 696d 7769 6b69 2f62 6173 652e 7669  /vimwiki/base.vi
00000d20: 6d2d 2020 6c65 7420 6d61 7463 685f 6c69  m-  let match_li
00000d30: 6e65 203d 2073 6561 7263 6828 613a 7769  ne = search(a:wi
00000d40: 6b69 5278 2c20 2773 272e 613a 636d 6429  kiRx, 's'.a:cmd)
00000d50: 0a

**Comment by hq6** [comment] 2019-03-21 01:09
Your line endings look normal for a Mac and I have not been able to reproduce the problem.
I can only suggest trying to re-install the plugin, but I suspect it is a problem caused by an OS setting, since Vim is clearly not able to parse the file correctly.

**Comment by jonathonpday** [comment] 2019-03-21 01:47
Thanks for the look will try later :)

**Comment by ranebrown** [comment] 2019-03-22 03:20
@jonathonpday I just created a new [troubleshooting page](https://github.com/vimwiki/vimwiki/wiki/Troubleshooting) with some steps you can try.

**Comment by jonathonpday** [comment] 2019-03-22 06:43
@ranebrown Hi, I have just followed the troubleshooting instructions as suggested and that does seem to have removed the error and backspace now works normally. That seems to indicate a configuration issue, but I am not sure how to proceed?

**Comment by jonathonpday** [comment] 2019-03-22 07:03
@ranebrown is there a way to mirror the Vimeo minimal setup with dropbox and I can see if that works?

**Comment by ranebrown** [comment] 2019-03-22 15:56
You need to use a vimrc at `~/.vimrc` unless you use the `-u` option to point to a different one as done on the troubleshooting page. Take a look at `:h startup` point 3. You might also be interested in something like [this](https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/). I'm going to close this issue but feel free to comment here if needed.

**Closed by ranebrown** 2019-03-22 15:56 UTC
Labels: need-more-info

**Comment by jonathonpday** [comment] 2019-03-22 18:28
@ranebrown Hi, I think I am very close to resolving the issue if I could possibly just ask for one more insight.

1) I have removed vimwiki directories from my machines and placed them purely in  Dropbox.

2) I have alos placed my `vimrc.vim` file in Dropbox as well which contins the following settings:

```
set number
syntax on
set tabstop=2
set softtabstop=2
set expandtab
set cursorline
set showmatch
set wildmenu
colorscheme slate
filetype indent on
filetype plugin on
set nocompatible
set backspace=indent,eol,start
let g:vimwiki_list = [{'path': '$HOME/Dropbox/vimwiki'}] 
```

4) This remote `vimrc.vim` is accessed via the local `vimrc` which contains only the following:

```
set runtimepath^=$HOME/Dropbox/vim
source $HOME/Dropbox/vim/vimrc.vim 
``` 

5) As you can see the remote `vimrc.vim` contains a path for vimwiki to route to the vimwiki directory  located in Dropbox (~/Dropbox/vimwiki). This works on my work Linux machine.

On my Macbook I am no longer getting errors but everytime I start vimwiki it asks me to start a new directory in ~/usr/vimwiki rather than use the rmote path.

Could you help me with this as I feel I am very close to resolving the issue.

Thank you again for all your help so far.

**Comment by ranebrown** [comment] 2019-03-23 11:45
What do you have in `$HOME/Dropbox/vim` other than your `vimrc`? Is there a reason you are adding that you your runtime path?

There might be a conflict if you have the vimwiki plugin in multiple locations like `$HOME/.vim/pack/plugins/start/` and somewhere else.

Maybe try renaming your `.vim` directory and then recreating a new one to start from scratch.

**Comment by 777uliahshafar** [comment] 2020-10-18 21:37
I use alt backspace in mac to get back to index wiki, thanks
