### ISSUE TITLE
Offering help with the project. :)

### ISSUE THREAD

**Issue by pjf** [vimwiki/vimwiki#300] opened 2017-02-12 06:48 UTC
Hello fabulous people! I've been using vimwiki a *lot* in the last few weeks, and I'd love to help out as best I can with the project. While my vimscript skills aren't great, I've decades of experience in triaging bugs, reviewing code, merging duplicate issues, and generally helping out with project maintenance in general.

If by any chance you want a hand working through issues backlogs and reviewing PRs, I'm very happy to do that. With a collaborator bit I can apply tags and close duplicates, but I'm happy to work without one if you're happy with me jotting down what you think should happen with each one.

Many thanks again for an amazing tool!

~ Paul

**Comment by pjf** [comment] 2017-02-12 06:52
And I'm off to a good start showing off my skills in github creating an empty issue in my enthusiasm. :) Sorry @EinfachToll and co if you got an empty email from github. x_x

**Comment by EinfachToll** [comment] 2017-02-12 13:08
Don't worry about emails, I turned mail notification off ;)

The thing is, I am in the middle of refactoring much of the internal structure of Vimwiki. Here is the relevant issue: https://github.com/vimwiki/vimwiki/issues/256
Until this is finished it makes not much sense to care about other things.
If you want to do something, you can check out the branch https://github.com/vimwiki/vimwiki/tree/refactor-internal-state-handling and test for regression bugs. Things to look out for are for example if everything works when you have multiple wikis with different syntaxes, temporary wikis, strange Vim settings and so on.
Other than that, feel free to take a look at issues and PRs and to ask questions.

**Comment by EinfachToll** [comment] 2017-02-12 13:10
Closing this issue, because there is no actual issue. You can of course still comment here.

**Closed** 2017-02-12 13:09 UTC

**Comment by pjf** [comment] 2017-02-13 05:44
> If you want to do something, you can check out the branch https://github.com/vimwiki/vimwiki/tree/refactor-internal-state-handling and test for regression bugs. Things to look out for are for example if everything works when you have multiple wikis with different syntaxes, temporary wikis, strange Vim settings and so on.

This I can definitely do. And since I have three wikis I use regularly (two in markdown, one in native vimwiki format), I'm guessing I'm a reasonable testing candidate. I've flipped my vimwiki install to the new branch now. :)

>  Until this is finished it makes not much sense to care about other things.

Unless those other things can land in the new branch reasonably unchanged, or are administrative rather than technical in nature, right? There are a few documentation fixes open (#266, #270, #297), some issues that look like they're resolved (#281), some PRs which could be edited to clarify what they're addressing (#273), PRs that could be cleaned of spurious commits and whitespace changes (#273 again), and many many issues that could be tagged with bug/enhancement/question and severity (if we want severity ratings). 

Some PRs look like they're against things like markdown rendering (#273) and windows compatibility (#269), which may apply cleanly to the new vimwiki structure without changes.

Without a contributor-bit I can note all these down in PRs and issues where I find them, although a lot of that feels like *giving* you work rather than actually doing the work. I don't want to be merging PRs, but I'm certainly happy to review them where they're within my knowledge-scope, and create appropriately cherry-picked/merged PRs to present bugfixes to the new branch as appropriate, or otherwise apply git-fu directly if desired. (I'm using to running projects with 200+ contributors, so I'm used to slinging code across multiple branches in trackable and verifiable ways.)

Many thanks again for all your hard work on vimwiki, it's made a huge increase to my productivity!

~ Paul
