### ISSUE TITLE
Apostrophe in link causes error

### ISSUE THREAD

**Issue by Flurrywinde** [vimwiki/vimwiki#339] opened 2017-04-22 18:35 UTC
I have a file with an apostrophe in its name. Example: `A dog's life.wiki`. So then a link to it looks like so: `[[A dog's life]]`.

If I hit Enter on this link to open that file, I get:
>E79: Cannot expand wildcards.

**Comment by Nudin** [comment] 2017-11-04 00:02
I cannot reproduce this. Does it still occur? If so, what format are you using?

**Comment by Flurrywinde** [comment] 2017-11-04 01:21
Yes, it still occurs. What do you mean by "format"? Doing a `git log`, I get: `commit 976cbbcd23dcd19ddb5dc5544645da8a51dbdfe6` as the latest, which was July 15, 2017. Is the latest version stable? If so, I could upgrade to it and check again.

**Comment by Nudin** [comment] 2017-11-04 01:49
By format I mean if you use vimwiki-, markdown or mediawiki-formating – if you havn't set in you vimrc it's vimwiki-syntax. 976cb is not that old, it's save to upgrade – but it shouldn't matter.

Does it really occur on pressing Enter on the text `[[A dog's life]]` or is the text in your case different (another special character)? What's your operating-system and filesystem?

I know of a bug causing `+` on text with a tick not to work (#394), but didn't yet manage to reproduce this.

**Comment by Nudin** [comment] 2017-11-04 02:03
And are you really using `'` and not <code>` </code>?

**Comment by Flurrywinde** [comment] 2017-11-04 08:18
1. I originally did not set a format, but I have now reproduced the bug with `syntax` set to both 'markdown' and 'media'. I set it as follows: `let g:vimwiki_list = [{'path': '~/vwapos/', \ 'syntax': 'markdown', 'ext': '.md'}]` in a brand new `git clone` of the latest vimwiki code and minimal .vimrc with no other plugins besides vimwiki (and pathogen to load it). I quit vim and ran it again after each change to my .vimrc.

2. Yes, it is really a regular apostrophe.

3. I am using Ubuntu 16.04 with ext4 filesystem.

4. If I select text in visual mode that is not yet a link and then hit enter to make it a link, if it has an apostrophe, I get the following messages:

`Error detected while processing function vimwiki#base#normalize_link[9]..<SNR>28_normalize_link_syntax_v:
line 14:
E15: Invalid expression: 'a dog's life'
Error detected while processing function vimwiki#base#normalize_link:
line 9:
E171: Missing :endif`

**Comment by Nudin** [comment] 2017-12-05 13:03
Still not able to reproduce. However the error points to base.vim line 2011, where I've build in a safesubstitute-call with #410. So this could/should be fixed now. Can you try again with latest version (75fe1d)

**Comment by Flurrywinde** [comment] 2017-12-05 19:29
This was fixed after the changes made in: https://github.com/vimwiki/vimwiki/issues/338 . Thanks!

**Closed** 2017-12-05 19:42 UTC
Labels: need-more-info

**Comment by madranet** [comment] 2020-05-03 10:00
---
OSX 10,14,4
nvim v0,4,3
---

I've just run into this same problem today.  For example, when trying to link to a file named `#wanderbury - Wanderbury's Chief.md`, when I highlight the `#wanderbury - Wanderbury's Chief` text and hit RETURN I get:

```
Error detected while processing function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link[8]..<SNR>4
8_normalize_link_syntax_v:
line   11:
E15: Invalid expression: '#wanderbury - Wanderbury's Chief'
Error detected while processing function vimwiki#base#normalize_link[3]..vimwiki#markdown_base#normalize_link:
line    8:
E171: Missing :endif
Error detected while processing function vimwiki#base#normalize_link:
line    3:
E171: Missing :endif
```

[The wiki filenames all begin with _#\<sometag>_ because they were exported from [NValt](https://brettterpstra.com/projects/nvalt/) where the hashtag is part of the note title. But it's the apostrophe that's causing the problem, as VimWiki had no problems with any of the other files which didn't have an apostrophe in the title].
