### ISSUE TITLE
VimwikiGenerateLinks error E65: Illegal back reference

### ISSUE THREAD

**Issue by patdavid** [vimwiki/vimwiki#1018] opened 2020-09-20 03:09 UTC
On `Stable version 2.5`.

Running `VimwikiGenerateLinks` with no `[pattern]` fails with this error message:

```
Error detected while processing function vimwiki#base#generate_links[45]..vimwiki#base#update_listing_in_buffer[79]..5[11]..vimwiki#base#is_diary_file:
line    4:
E65: Illegal back reference
Error detected while processing function vimwiki#base#generate_links[45]..vimwiki#base#update_listing_in_buffer:
line   79:
E714: List required

```

My relevant `.vimrc` section for vimwiki:

```
let wiki_1 = {}
let wiki_1.path = '~/Nextcloud/vimwiki/' 
let wiki_1.path_html = '~/Nextcloud/vimwiki/export/html/'
let wiki_1.syntax = 'markdown' 
let wiki_1.ext = '.md'
"let wiki_1.vimwiki_markdown_link_ext = 1
let wiki_1.auto_diary_index = 1
let wiki_1.auto_toc = 1
let wiki_1.auto_tags = 1

let wiki_2 = {}
let wiki_2.path = '~/Nextcloud/vimwiki-work/'
let wiki_2.path_html = '~/Nextcloud/vimwiki-work/export/html/'
let wiki_2.syntax = 'markdown'
let wiki_2.ext = '.md'
"let wiki_2.vimwiki_markdown_link_ext = 1
let wiki_2.auto_diary_index = 1
let wiki_2.auto_toc = 1
let wiki_2.auto_tags =  1

let g:vimwiki_list = [wiki_1, wiki_2]
let g:vimwiki_markdown_link_ext=1
let g:vimwiki_global_ext=0

```

**Comment by patdavid** [comment] 2020-09-21 15:46
Aha, checking a little more, this appears to be happening in GVim on my Windows machine, but not when using Cygwin on the same machine.

I added `echom` the file that was borking things:

```
...
...
Writing - pixls.us
bash
diary\2019-09-01
Error detected while processing function vimwiki#base#generate_links[46]..vimwiki#base#update_listing_in_buffer[79]..3[12]..vimwiki#base#is_diary_file:
line    4:
E65: Illegal back reference
Error detected while processing function vimwiki#base#generate_links[46]..vimwiki#base#update_listing_in_buffer:
line   79:
E714: List required
```

In Cygwin (where `VimwikiGenerateLinks` works as expected):
```
...
...
Writing - pixls.us
bash
diary/2019-09-01
diary/2019-09-14

```

So it appears to be a path separator issue (`/` vs `\`).  Not sure where/how best to handle this for windows users.  Any suggestions?

**Comment by patdavid** [comment] 2020-09-21 16:25
It seems this might be related in some way to https://github.com/vimwiki/vimwiki/issues/478?

**Comment by tinmarino** [comment] 2021-05-17 15:03
This should be fixed in the dev branch. I cannot reproduce the bug.
Please use the dev branch. If bug still exit  reopen pasting the output of VimwikiShowVersion.
In case it is configuration related, please spot (dichotomizing) the minimal configuration required to reproduce the bug.

**Closed by tinmarino** 2021-05-17 15:03 UTC
Labels: bug
