### ISSUE TITLE
Request: vimwiki doesn't hijack markdown files by default

### ISSUE THREAD

**Issue by guo-sun** [vimwiki/vimwiki#927] opened 2020-06-25 21:27 UTC
I use markdown files outside of a vimwiki context, but now they're all being treated as vimwiki files. Temporary wikis are being created when I try to e.g. create a new diary note.

I have `let g:vimwiki_global_ext = 0` in my vimrc and no other vimwiki options set. According to [this comment](https://github.com/vimwiki/vimwiki/issues/871#issuecomment-628341340) I would only expect to see this behavior if I have syntax set to 'markdown', rather than the default 'default'.

I see the same behavior on both master and dev branches. Vimwiki stable version 2.5

**Comment by suliveevil** [comment] 2020-06-27 20:49
+1
FoldMethod and Syntax is conflicting with my other awesome plugins: vim-fold-cycle FoldText.

**Comment by NerdsvilleCEO** [comment] 2020-07-05 03:53
This also is affecting `vim-markdown` using vim default folding.

**Comment by davy79** [comment] 2020-07-26 20:28
Same issue here. all markdown files are set to filetype=vimwiki... even though I'm using the default vimwiki syntax for my vimwiki...

**Comment by ecly** [comment] 2020-08-12 13:57
+1 would be nice to be able to handle markdown files outside of vimwiki context with separate plugins.

**Comment by tinmarino** [comment] 2020-08-13 04:59
I cannot repeat your bug => please do those tests : I am lost and this seems to be a serious bug so if someone can help me analyse this giving a detailed repeatable bug, follow those steps:

### Ensure the bug is in your side

* Rebase to the dev branch (top): see this commit: 659ca62b292fc8a48028728469726139e1c77033
* `let g:vimwiki_global_ext = 0` __Before__ packadd vimwiki

### Tests

1. Doing `vi file.md` outside of a wiki folder and `:set ft?` => Should output markdow
2. Doing `vi wiki/index.md` and pressnig enter to redirect to say `../file.md`, then `:set ft?` => Sould return markdown
3. Doing `vi wiki.wiki` then `:set ft?` => Nothing

### Code

The problem must comes from plugin, it is just 500 lines, the check is in s:setup_new_wiki_buffer

in plugin: https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/plugin/vimwiki.vim#L70-L82

But some autocommands are not passing thought it so will triger even if you do not want : https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/plugin/vimwiki.vim#L310-L341

So @suliveevil is right, if can affect folds in case: `if vimwiki#vars#get_global('folding') =~? ':quick$'` 

### Debug

The filetype set with vimwiki#u#ft_set so 

```
breakadd func vimwiki#u#ft_set
```

play around, when it break `next next next next` to see where that comes from

__Good luck team!__

**Comment by davy79** [comment] 2020-08-17 14:30
FYI:

I just tried the above tests...

checked out the dev branch and:

test 1. returns `vimwiki`
test 2. returns `vimwiki`
test 3. returns `vimwiki`

Then I added `let g:vimwiki_global_ext = 0` to my vimrc and this seems to do the trick...

any .md file is now set to `ft=markdown`

Just to be sure I opened my vimWiki and that is still set to `ft=vimwiki` :-) so all good.

I don't use folding so can't comment on that...

**Comment by tinmarino** [comment] 2020-08-17 14:57
Thanks @davy79 for your feedback.

**Comment by tinmarino** [comment] 2020-08-24 05:46
I am closing: cannnot reproduce any issue, feel free to open a new one and explain a repetible procedure with a minimal vimrc with the dev branch code

**Closed by tinmarino** 2020-08-24 05:46 UTC
Labels: bug, config, markdown

**Comment by SoaresAlisson** [comment] 2023-08-10 16:22
I had the same issue yesterday. What solved to me was changing the order of lines in my init.vim / .vimrc, putting the diary lines before the markdown ones.

```
let g:vimwiki_list = [{'auto_diary_index': 1}]
let g:vimwiki_global_ext = 0
let g:vimwiki_list = [{'path': '~/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
```
