### ISSUE TITLE
VimWiki not respecting path

### ISSUE THREAD

**Issue by lukeberry99** [vimwiki/vimwiki#1149] opened 2021-07-08 00:49 UTC
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
```lua
        use {
          "vimwiki/vimwiki",
          config = function()
            vim.g.vimwiki_list = {
              {
                path = '/home/luke/Documents/personal/wiki'
              }
            }
          end
        }

```
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
I've set my config as above and when I use `<leader>ww`  VimWiki asks me if I want to create a new directory in `/home/luke/vimwiki` instead of respecting the path I have set.
- [x] Include the output of `:VimwikiShowVersion`.
`Stable version: 2.5`

**Comment by brennen** [comment] 2021-08-28 18:44
I'm guessing that's nvim Lua config?

One thought is that there might be something subtly wrong with the data structure, but I'm not terribly familiar with Lua or how nvim uses it for config...

**Comment by brennen** [comment] 2021-08-30 05:39
Looks like this is a duplicate of #1130.

**Closed by brennen** 2021-08-30 05:39 UTC
Labels: question, neovim
