### ISSUE TITLE
Adding new column to existing table fails

### ISSUE THREAD

**Issue by beuerle** [vimwiki/vimwiki#655] opened 2019-04-03 08:52 UTC
- sitting on the dev branch with the most recent commit e0fffb4 (not able to run `:VimwikiShowVersion`, see #654).
- markdown syntax
- vimwiki related settings in my vimrc:
```vim
let g:vimwiki_markdown_link_ext = 1
let g:vimwiki_markdown_header_style = 1
let g:vimwiki_folding = 'expr'
let g:vimwiki_hl_headers = 1
let g:vimwiki_hl_cb_checked = 1
let g:vimwiki_list_margin = 0
```

---

Since recently adding a new column to an existing table does not work anymore:

1. Create new table

![2019-04-03_10:47:06](https://user-images.githubusercontent.com/10122039/55465677-eba42200-55fd-11e9-9d07-3faf2dfa1aa4.png)

2. Add column to existing table (same behaviour when trying to add to all rows):

![2019-04-03_10:47:14](https://user-images.githubusercontent.com/10122039/55465676-eba42200-55fd-11e9-8f1d-782cf1d8f34b.png)

Going back to normal mode used to add a new column to the table. However, now it throws an error:

![2019-04-03_10:47:18](https://user-images.githubusercontent.com/10122039/55465675-eb0b8b80-55fd-11e9-80a4-1e0643f5a2fb.png)

and no added column appears:

![2019-04-03_10:47:27](https://user-images.githubusercontent.com/10122039/55465673-eb0b8b80-55fd-11e9-954f-ff2a86d8d282.png)

Here is the relevant vim message:

```vim
Error detected while processing function vimwiki#tbl#format[27]..<SNR>127_get_alig
ned_rows[47]..<SNR>127_fmt_row:
line   14:
E716: Key not present in Dictionary: 1
Error detected while processing function vimwiki#tbl#format[27]..<SNR>127_get_alig
ned_rows[47]..<SNR>127_fmt_row:
line   14:
E116: Invalid arguments for function s:fmt_cell('', a:max_lens[idx], a:aligns[idx]
).s:rxSep()
Error detected while processing function vimwiki#tbl#format[27]..<SNR>127_get_alig
ned_rows[45]..<SNR>127_fmt_sep:
line    8:
E716: Key not present in Dictionary: 1
Error detected while processing function vimwiki#tbl#format[27]..<SNR>127_get_alig
ned_rows[45]..<SNR>127_fmt_sep:
line    8:
E116: Invalid arguments for function s:fmt_cell_sep(a:max_lens[idx], a:aligns[idx]
).s:rxSep()
Error detected while processing function vimwiki#tbl#format[27]..<SNR>127_get_alig
ned_rows[47]..<SNR>127_fmt_row:
line    9:
E716: Key not present in Dictionary: 1
Error detected while processing function vimwiki#tbl#format[27]..<SNR>127_get_alig
ned_rows[47]..<SNR>127_fmt_row:
line    9:
E116: Invalid arguments for function s:fmt_cell(value, a:max_lens[idx], a:aligns[i
dx]).s:rxSep()
```

**Comment by ranebrown** [comment] 2019-04-03 12:55
Looks like this is related to the table alignment feature that was added with 23d273d54711035ac2b1c19838438521f0982595. @hq6 can you take a look at this since you worked on that previously?

**Comment by hq6** [comment] 2019-04-03 17:27
@ranebrown , Sure, I can take a look. I predict that this will bounce to the author of that commit after I bisect it.

**Comment by hq6** [comment] 2019-04-03 17:45
A git bisect indicates that `23d273d54711035ac2b1c19838438521f0982595` introduced this regression, which I merged in #377. 

@schmeisers, will you take a look?
I can try to fix it also, but I suspect you have more context.

**Comment by hq6** [comment] 2019-04-03 18:49
This should be fixed on `dev` with `3c0ae2ff970ea9cf338e667297f3ddd4b87ac806`.

**Closed by hq6** 2019-04-03 18:49 UTC

**Comment by ranebrown** [comment] 2019-04-03 22:16
@hq6 if you don't put the commit hash in a code block it automatically creates a link to that commit 😉

**Comment by hq6** [comment] 2019-04-03 22:44
@ranebrown , Thanks for the tip! Updated my comment.
