### ISSUE TITLE
Please support another standard markdown h1 syntax for diary generate links

### ISSUE THREAD

**Issue by yaohunzhanyue** [vimwiki/vimwiki#841] opened 2020-03-26 04:27 UTC
vimrc:
``` 
 'syntax': 'markdown',
  'ext':'.md',
```
example diary file 2020-03-25.md:
```
2020-03-25
==========

## contents
```
expect diary generate links:
```
# Diary

## 2020

### March
    * [2020-03-25](2020-03-25)
```
actually get these:
```
# Diary

## 2020

### March
    * [contents](2020-03-25)
```

**Comment by ranebrown** [comment] 2020-04-03 18:50
Do you see the same thing on the `dev` branch? There is also an option on the `dev` branch `diary_caption_level` that controls how the headers are generated.

**Comment by yaohunzhanyue** [comment] 2020-04-05 04:18
@ranebrown The problem is that vimwiki can't detect `===============` as caption, it will detect '#' symbol, but in markdown syntax, these two are the same.

**Comment by ranebrown** [comment] 2020-04-05 11:52
I see. This is a duplicate of #209. Sorry to say it isn't really a priority though.

**Closed by ranebrown** 2020-04-05 11:52 UTC
