### ISSUE TITLE
Markdown wiki compatibility

### ISSUE THREAD

**Issue by zimbatm** [vimwiki/vimwiki#1032] opened 2020-10-13 12:27 UTC
One downside of the `[[PageName]]` notation when using the Markdown syntax is that it doesn't render on GitHub. Transforming those into `[PageName](PageName.md)` links is also relatively tedious.

Today I found an interesting workaround in the [foam](https://github.com/foambubble/foam) project. What they do is generate a table a the bottom of the Markdown file.

Eg:

```
# Foam Blog
​
- [[2020-07-11-three-weeks-in]]

[//begin]: # "Autogenerated link references for markdown compatibility"
[2020-07-11-three-weeks-in]: blog/2020-07-11-three-weeks-in.md "Three Weeks In"
[//end]: # "Autogenerated link references"
```

Once converted to HTML, the link still contains one pair of the surrounding `[]`.

I thought that this approach was interesting and wanted to share with vimwiki.

**Comment by tinmarino** [comment] 2020-10-20 03:56
You are asking for [Link Reference definition](https://github.github.com/gfm/#link-reference-definitions) duplicate of #925

**Closed by tinmarino** 2020-10-20 03:56 UTC
