### ISSUE TITLE
g:vimwiki_table_mappings does not disable <tab> mappings on markdown syntax

### ISSUE THREAD

**Issue by emoriarty** [vimwiki/vimwiki#669] opened 2019-04-13 10:34 UTC
Using the option `g:vimwiki_table_mappings` set to 0 does not disable table mappings in INSERT mode as the documentation explains:

```vim
g:vimwiki_table_mappings

Enable/disable table mappings for INSERT mode.

Value           Description
0               Disable table mappings.
1               Enable table mappings.

Default: 1
```

The specific wiki that I am using is in markdown syntax.

```vim
let g:vimwiki_table_mappings=0
let g:vimwiki_list=[{'path': '~/Documents/notes', 'syntax': 'markdown', 'ext': '.md'}]
```

Also I have the UltiSnips plugin installed with the `<tab>` key set for snippet completion along other settings.

```vim
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<c-f>'
let g:UltiSnipsJumpBackwardTrigger='<c-b>'
```

Even using this setup UltiSnips tab does not work. After removing the option `g:vimwiki_list`the expected tab behaviour comes back.

I also checked this [issue](https://github.com/vimwiki/vimwiki/issues/357) but the solution proposed is precisely what is failing.

My current environment versions are:
Neovim: v0.3.4
VimWiki: 2.4

**Comment by ranebrown** [comment] 2019-04-13 12:31
@emoriarty The option `let g:vimwiki_table_mappings=0` works correctly for me in conjunction with Ultisnips. It is disabled [here](https://github.com/vimwiki/vimwiki/blob/6766c37ce09a623b3de7ddb86ca30278eea37a82/ftplugin/vimwiki.vim#L577-L581) based on the value of `g:vimwiki_table_mappings`.

After you open you wiki try `:imap` to see what `<Tab>` is mapped to. I only see `i  <Tab>       * <C-R>=UltiSnips#ExpandSnippet()<CR>`

**Comment by emoriarty** [comment] 2019-04-13 13:48
Hey @ranebrown! Thanks for your feedback.

The `:imap` output show the tab set to the expand snippet: `i  <Tab>       * <C-R>=UltiSnips#ExpandSnippet()<CR>`. Don't see any other mappings could collide with. 

I've checked what this [ticket](https://vi.stackexchange.com/questions/7722/how-to-debug-a-mapping) suggests (check if the terminal app or some other tool captures the event). Nothing seems to work except by removing the next line in the `.vimrc` and the `<tab>` capture works fine.
```vim
let g:vimwiki_list=[{'path': '~/Documents/notes', 'syntax': 'markdown', 'ext': '.md'}]
```
This makes me think the plugin in my current environment is doing something wrong. By the way, I also removed and installed the plugin (even installed the `dev` branch) multiple times and the result is always the same: don't work.

**Comment by ranebrown** [comment] 2019-04-13 15:52
I did try with markdown syntax. If you have your cursor in a table in insert mode and press tab does it jump to the next column or insert a tab?

Can you try the steps on the [troubleshooting page](https://github.com/vimwiki/vimwiki/wiki/Troubleshooting#minimal-vimrc) with these additions:
```vim
set runtimepath+=<path/to/ultisnips>
let g:vimwiki_table_mappings=0
```

**Comment by ranebrown** [comment] 2019-04-13 18:01
This seems to be specific to neovim. I can't any snippets to complete with our without vimwiki active. I don't use neovim so it is probably a configuration issue. Can you post your complete settings for neovim?

**Comment by emoriarty** [comment] 2019-04-13 23:06
I tried to change the column forward in insert mode and does not work. That means disabling the `g:vimwiki_table_mappings` option is working fine.

I've also create a new `.vimrc` with a bare minimal settings and fresh installation of the conflicting plugins. No matter vim or neovim the results happens to be the same: no snippet autocomplete when the `syntax` is set to `markdown` in the current used wiki.

I think the issue is related with the fact the UltiSnips maps a specific file extension with a snippets set. Because both plugin checks for file extension, perhaps in some way VimWiki `g:vimwiki_list` is overrides UltraSnips checker. But this is a supposition, some research should be done in that direction. At least one thing is sure, UltiSnips only stops working when the `g:viwiki_list` checks for markdown format.

**Comment by emoriarty** [comment] 2019-04-14 00:22
By the way, I almost forget. Here is my `.vimrc` setup.

```vim
" General {{{
set nocompatible    " Prevent vi compatibility, ensuring unexpected effects
set encoding=utf-8  " Default character encoding
set showcmd         " Displays commands entered in the file
set showmode        " Show current mode at bottom
set visualbell      " Use visual alert instead of sound
set history=50      " Sets how many lines of history VIM has to remember
set autoread        " Updates buffer when file changed externally
set backspace=eol,start,indent  " Backspace works as expected
set hidden          " Buffers are hidden automatically even if they are modified
let mapleader=" "   " Map leader allows default key to combine with other commands
filetype on  " Load file type specific settings
"}}}
" Plugins {{{
" Download vim-plug if is not present
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
"  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
" ndif
call plug#begin('~/.vim/plugged')
  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'tpope/vim-fugitive'
  Plug 'morhetz/gruvbox'
  Plug 'w0rp/ale'
  Plug 'vim-airline/vim-airline'
  Plug 'vimwiki/vimwiki'
  " syntax
  Plug 'mxw/vim-jsx'
  Plug 'pangloss/vim-javascript'
  Plug 'HerringtonDarkholme/yats.vim' 
  Plug 'elzr/vim-json'
  " Markdown
  Plug 'SirVer/ultisnips'
  Plug 'honza/vim-snippets'
  Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }}
call plug#end()
" gruvbox options
let g:gruvbox_bold=0
let g:gruvbox_italic=1
let g:gruvbox_contrast_light='hard'
let g:gruvbox_contrast_light='soft'
" Ale options
let g:ale_linters={
\ 'javascript': ['prettier', 'eslint'],
\}
let g:ale_fixers={
\ 'javascript': ['prettier', 'eslint'],
\}
let g:ale_linters_explicit=1
" Airline options
let g:airline_powerline_fonts=1
" CtrlP options
let g:ctrlp_working_path_mode=0
let g:ctrlp_custom_ignore='\v[\/]\.(git|hg|svn)$'
" VimWiki
let wiki = {}
let wiki.path = '~/vw_tmp/wiki'
let wiki.path_html = '~/vw_tmp/wiki/html'
let wiki.syntax = 'default'
let wiki.ext = '.wiki'
let g:vimwiki_table_mappings=0
let g:vimwiki_list=[wiki]
" UltiSnips
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<c-f>'
let g:UltiSnipsJumpBackwardTrigger='<c-b>'
"}}}
" Functions {{{
if !exists('*MKDir')
  function MKDir(path)
    silent execute '!mkdir '.a:path.' > /dev/null 2>&1'
  endfunction
endif
" }}}
" UI {{{
set ruler           " Show the line and column number of the cursor position
set relativenumber  " Shows the relative number from the current cursor position
set numberwidth=2   " Number of columns left for line numbers
set cursorline      " Draws an horizontal background or underline on the line the cursor is present
set nowrap          " Don't wrap lines
set lazyredraw      " Don't redraw screen if not needed 
"}}}
" Scrolling {{{
set scrolloff=8       " Screen lines to keep above and below the cursor when scrolling
set sidescrolloff=16  " Screen columns to keep left and right the cursor when side scrolling
set sidescroll=0      " Number of columns the scrolling moves off the screen
" }}}
" Indentation {{{
set tabstop=2     " Tab size
set shiftwidth=2  " Number of spaces when indenting
set expandtab     " Use spaces instead of tabs
set smarttab      " Smart tabs
set autoindent    " Auto indent
set smartindent   " Smart indent
"}}}
" Completion {{{
set wildmenu  " Enabling smart command line completion on wildcard (<Tab> by default)>
filetype plugin on
set omnifunc=syntaxcomplete#Complete
"}}}
" Menu {{{
"source $VIMRUNTIME/delmenu.vim  " Clearing all menus 
"source $VIMRUNTIME/menu.vim     " Lading default menus (default in gvim)
"}}}
" Mappings {{{
"set wildcharm=<tab>             " Sets the key <Ctrl-Z> as a wildcard for mappings and macros executing the autocompletion
" :emenu is executed when typing <F4> along with the autocompletion
"map <F4> :emenu <tab>
" Split window and jump to it
nnoremap <Leader>w <C-w>v<C-w>l " vertical split on the right
nnoremap <Leader>s <C-w>s<C-w>j " horizontal split at bottom
" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
" Strip all trailing whitespace in current file
nnoremap <Leader>W :%s/\s\+$//<cr>:let @/=''<CR>
" Clean highlight search results
nnoremap <leader>, :noh<cr>
" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
" Switch between the last two files
nnoremap <leader><leader> <c-^>
"}}}
" Searching {{{
set ignorecase  " Allows searching not being case-sensitive
set smartcase   " Search patterns with uppercase letters are case-sensitive
set hlsearch    " Highlights all matches
set incsearch   " Incremental search: match first result as you type search pattern
" Ignore next file patterns when searching and completion
set wildignore=*/node_modules/*
set include+=^import.*from.'\zs.*\ze'
"}}}
" Colors {{{
syntax enable " Setting on default syntax colors
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
colorscheme gruvbox
set background=dark
"}}}
" Filetype {{{
filetype indent on  " Load specific settings based on file type
"}}}
" Backups {{{
call MKDir('~/.vim/cache')
call MKDir('~/.vim/cache/swap')
call MKDir('~/.vim/cache/backup')
call MKDir('~/.vim/cache/undo')
set directory^=~/.vim/cache/swap//    " Swap files are stored in provided path
set backupdir^=~/.vim/cache/backup//  " Backup files are store in provided path
set undodir^=~/.vim/cache/undo//      " Undo files are stored in provided path
set backup    " Enables next option if you like to persist backup files
set undofile  " Enables storing undo history per file
"}}}
" Windows {{{
set splitbelow  " Open new split below
set splitright  " Open new vertical split right
" }}}
" Extra {{{
" vim:foldmethod=marker:foldlevel=0
"}}}
```

**Comment by ranebrown** [comment] 2019-04-14 04:12
Using the settings you posted works unless you change these two lines to `markdown` and `.md`?
```vim
let wiki.syntax = 'default'
let wiki.ext = '.wiki'
```
Have you tried with everything removed from your `.vimrc` except vimwiki and ultisnips settings? In the settings you posted there is a bunch of other stuff that should be removed for testing.

**Comment by emoriarty** [comment] 2019-04-14 08:14
> Using the settings you posted works unless you change these two lines to `markdown` and `.md`?
> 
> ```viml
> let wiki.syntax = 'default'
> let wiki.ext = '.wiki'
> ```
> 
> Have you tried with everything removed from your `.vimrc` except vimwiki and ultisnips settings? In the settings you posted there is a bunch of other stuff that should be removed for testing.

**Comment by emoriarty** [comment] 2019-04-14 08:25
Ups! I closed accidentally the ticket. It's reopened again.

> Using the settings you posted works unless you change these two lines to `markdown` and `.md`?
> 
> ```viml
> let wiki.syntax = 'default'
> let wiki.ext = '.wiki'
> ```
That's right. Once they change to markdown, UltiSnips does not work.

> Have you tried with everything removed from your `.vimrc` except vimwiki and ultisnips settings? In the settings you posted there is a bunch of other stuff that should be removed for testing.

The .vimrc I shared here is the original one. If you read the previous [comment](#issuecomment-482896900) you'll see the testing was done with a fresh .vimrc. The settings are just below these lines.

```vim
set nocompatible
filetype plugin on
syntax on
set runtimepath+=~/vw_tmp/vimwiki
set runtimepath+=~/vw_tmp/ultisnips
set runtimepath+=~/vw_tmp/vim-snippets
let wiki = {}
let wiki.path = '~/vw_tmp/wiki'
let wiki.path_html = '~/vw_tmp/wiki/html'
let wiki.syntax = 'markdown'
let wiki.ext = '.md'
let g:vimwiki_list = [wiki]
let g:vimwiki_table_mappings=1
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<c-f>'
let g:UltiSnipsJumpBackwardTrigger='<c-b>'
```

**Comment by ranebrown** [comment] 2019-04-14 12:29
I can't reproduce this. With the minimal settings you posted snippets do not work since `let g:vimwiki_table_mappings=1` is set to 1 and tab is remapped by vimwiki. If I set that option to `0` or I use a different trigger like `let g:UltiSnipsExpandTrigger='<C-e'` snippets work correctly.

**Comment by emoriarty** [comment] 2019-04-14 15:56
I already know what is happening. The snippet expansion is not working (at least in my machine) because after appending in the `g:vimwiki_list` with a _markdown_ format, all _markdown_ files are treated as _vimwiki_ file types. This can be easily checked by running the next command in the vim console.
```vim
:echo &filetype " returns vimwiki instead markdown
```
I got here after doing some reverse engineering in the UltiSnips plugin. It took me to where the library checks if the file type being edited matches with one of the snippets sets registered. Therefore when the file type returned is vimwiki, the expand function is not going to return anything: the snippet belongs to markdown not vimwiki.

What I still don't know is why vimwiki is changing the file type. Do you have an idea how this is possible  @ranebrown ?

**Comment by ranebrown** [comment] 2019-04-14 17:09
Vimwiki is a filetype plugin and its correct operation requires that the filetype be set to vimwiki. You can take a look at this [experimental branch](https://github.com/vimwiki/vimwiki/tree/multi_ft) and the operation explained in #461. You might also be interested in `UltisnipsAddFiletypes`. I'm going to close this since this isn't a vimwiki bug. Feel free to continue posting here with any additional information or questions.

**Closed by ranebrown** 2019-04-14 17:09 UTC
Labels: neovim

**Comment by emoriarty** [comment] 2019-04-15 06:38
I got to one of the solution in the post you've shared. Changing the file type by hand for at least make work the snippets.

Thanks for the `UltisnipsAddFiletypes` tip. That probably will do.

Anyway I think this is a bug. An intended one, you knew already about the file type modification. When the operation involves changing a file type in order to work, you cannot expect another features (plugins) relying on the file type to work won't break. I guess you had estimated the decision to make this change but no matter it is documented or not, it's not a good software decision. I'm sure other alternatives would have prevented this scenario.

In any case the debugging of this issue is not being a waste of time. At least now I understand better how vim manages plugins. I hope you'll come along a better solution than changing the file type.

**Comment by ranebrown** [comment] 2019-04-15 14:33
> Anyway I think this is a bug.
> no matter it is documented or not, it's not a good software decision

Yeah, well, you know, that's just, like, your opinion, man.

**Comment by lpanebr** [comment] 2020-04-29 20:18
I managed to fix my vimwiki ultisnippets by changing the vimwiki file extension to `.mdvimwiki` and registering it with @ranebrown the `UltisnipsAddFiletypes` tip. 

**I did not need** the `let g:vimwiki_table_mappings = 0`.

This is what I added to my vim.init:

```vim
autocmd FileType mdvimwiki UltiSnipsAddFiletypes vimwiki

" use my custom folder, markdown syntax and custom extension
let g:vimwiki_list = [{'path': '~/.config/mynotes/',
                    \ 'syntax': 'markdown', 'ext': '.mdvimwiki'}]
```

**Comment by nathanbraun** [comment] 2020-08-03 15:37
I think I had this problem too, I dealt with it by putting;

```
iunmap <buffer> <Tab>
```

in .config/nvim/after/ftplugin/vimwiki.vim
