### ISSUE TITLE
Can't follow a link if wildignore is invalid

### ISSUE THREAD

**Issue by sato-s** [vimwiki/vimwiki#1184] opened 2021-11-05 20:25 UTC
My vimwiki doesn't follow a link at all without any error messages.
I noticed my `.vimrc` had `set wildignore=,,` which is not proper setting.
If this breaks vimwiki's behavior completely, a helpful error message would be nice.

Here is a minimum `.vimrc` to reproduce this.

```
call plug#begin()
Plug 'vimwiki/vimwiki'
call plug#end()

set wildignore=,,
```

###  :VimwikiShowVersion
```
Os: Linux
Vim: 800
Branch: dev
Revision: a3a3fbf
Date: 2021-09-20 11:16:56 -0600
```

### Syntax

default

### Check List

Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

**Comment by tinmarino** [comment] 2021-12-18 15:47
Closing <= cannot reproduce in dev

**Closed by tinmarino** 2021-12-18 15:47 UTC
