### ISSUE TITLE
Unsupported math fonts

### ISSUE THREAD

**Issue by stevenwalton** [vimwiki/vimwiki#267] opened 2016-12-12 22:33 UTC
From what I can tell some simple math commands are accepted but others aren't. Such as a fraction or square root.
```
{{$
\frac{1}{2}
\sqrt{a^2 + b^2}
\int_0^\infty x dx
e^{-\sigma n x}
}}$
```
All work in weird ways, but I get Greek letters working properly. `frac` and `sqrt` just doesn't work, and the integral one does a subscript for 0 but not a superscript for infinity. The last exponential superscripts the negative, n, and x only, but does not render the sigma nor does it superscript it -  `\sigma` alone renders to the proper symbol. I would think simple functions would be supported, and the documentation does suggest that it should, considering MathJax supports these functions. But maybe I missed something. 

I do see these working properly in the browser, but not in the console. I am wondering if it is a font issue with things like `\sqrt`, or if it is just not mapped. As for `\frac` I think it could easily just be mapped to `\frac{a}{b}` -> `(a)/(b)`.

It would also be nice if the javascript that is needed to view was added to the page automatically to the html generated doc.

**Comment by stevenwalton** [comment] 2016-12-13 19:22
Through more usage I'd also like to note some strange cases. Such as with this line
```
{{$
L_{rad} = \frac{1}{n\sigma_{brems}} = \frac{1}{4(\frac{Z^2 n}{137})r_0^2ln(\frac{183}{Z^{\frac{1}{3}})
}}$
```
A little complex, but things look fine in the html file, but there are some strange effects in the vim formatting. I have linked a ![picture](http://imgur.com/a/TfGKB) for convenience. 

Things that can be noticed is that that `ra` in `L_{rad}` are subscripted but the d isn't. Also the `ra` has a space between them. A similar thing happens with `\sigma_{brems}`. Another weird issue is that when doing fractional powers is that `Z^\frac{1}{3}` becomes `Z\frac{1}{3}`. This creates extremely confusing lines, as not only are the fonts strange but I lost meaningful symbols. Is this a font thing on my end or is it something everyone is viewing?

**Comment by hq6** [comment] 2019-04-15 17:26
I was able to reproduce this issue, but I suspect it will be nontrivial to fully fix, because it likely depends on what fonts are available to Vim. 

PR's are welcome if you want to try though!

**Comment by ranebrown** [comment] 2019-04-17 01:06
Vimwiki isn' actually responsible for math highlighting and character concealing (which is how subscripts etc. work). That is all done by `tex.vim` which is shipped with vim. If you open a `file.tex` and paste the same formulas you will see the same issues. See [these lines](https://github.com/vimwiki/vimwiki/blob/750b3171b321872c17b88237db12822fc3e8c264/autoload/vimwiki/base.vim#L1037-L1048) for how we implement it.

Other plugins such as vim-pandoc have the [same issue](https://github.com/vim-pandoc/vim-pandoc/issues/85).

#428 is also a similar problem.

**Comment by hq6** [comment] 2019-04-17 17:21
Since this appears to be orthogonal to Vimwiki itself, I am closing this issue.

**Closed by hq6** 2019-04-17 17:21 UTC
