### ISSUE TITLE
:VimwikiBacklinks does not find any links to file

### ISSUE THREAD

**Issue by bernhard42** [vimwiki/vimwiki#413] opened 2017-11-15 14:29 UTC
When using :VimwikiBacklinks or :VWB all I get is the message "Vimwiki: No other file links to this file". I verified that there a working links to the wiki file and it still doesn't work. It's the same with wiki style ("[[]]") links and links with markdown syntax ("[]()").

**Comment by Nudin** [comment] 2017-12-04 15:38
In my short test it seems to work with mediawiki/vimwiki-syntax but not with markdown syntax. Can you check again that it's also not working with vimwiki-syntax?

**Comment by bernhard42** [comment] 2017-12-07 07:45
It works fine under macOS using MacVim with _both_ syntax versions and even links like "[][]".
I also tried it using gVim on Windows 7 and it didn't work at all.

**Comment by Nudin** [comment] 2017-12-09 17:07
I looked into the code and there's definitely a issue with the markdown-syntax – it's even noted in the [code as todo](https://github.com/vimwiki/vimwiki/blob/75fe1d4f003f77a33955f436e023a4ce9548cb69/syntax/omnipresent_syntax.vim#L23) one should modify the regexp so that it matches all forms of valid links.
I tried shortly, but vim-regexp is a bit different than perl/sed, and I wasn't yet successful…
Maybe it's also better to wait fixing this until the refactoring is done. :/

**Comment by bernhard42** [comment] 2017-12-11 23:35
Any idea on when the refactoring might be finished?

I'm still wondering why it works with MacVim and doesn't with gVim on Windows 7. Is there a way to watch where vimwiki is searching (debugger or something similar)? Maybe it's an issue with unicode and filename encodings or things like that.

**Comment by Nudin** [comment] 2017-12-11 23:54
> Any idea on when the refactoring might be finished?

Sadly no. :( It's quite far, but the only dev that is into it, has no time at the moment…

> I'm still wondering why it works with MacVim and doesn't with gVim on Windows 7. Is there a way to watch where vimwiki is searching (debugger or something similar)? Maybe it's an issue with unicode and filename encodings or things like that.

Yes:
```
:echo vimwiki#base#find_files(0, 0)
:echo vimwiki#base#find_files(1, 0)
```
will list all files from wiki 0 (the first wiki), respective the second wiki.

If you add 
```
function! vimwiki#base#test(wikifile, idx)
  return s:get_links(a:wikifile, a:idx)
endfunction
```
to the file autoload/vimwiki/base.vim in your vimwiki-installation, you can look which links it detects in a file by running:
```
:echo vimwiki#base#test("path/to/file", 0)
```
(again the 0 is the number of the wiki).

**Comment by ranebrown** [comment] 2019-03-24 13:16
`:VWB` seems to work correctly for default and markdown syntax on a Mac. Tested the same on windows and it does not work. I would guess this is related to path handling (#478) so I'm going to set this as low priority until that is complete.

**Comment by ranebrown** [comment] 2019-04-06 16:47
@bernhard42 Do you mind testing the fix I pushed to the `dev` branch on Windows? Thanks!

**Comment by bernhard42** [comment] 2019-04-08 16:49
> @bernhard42 Do you mind testing the fix I pushed to the `dev` branch on Windows? Thanks!

Might take a few days but I will test it.

**Comment by ranebrown** [comment] 2019-04-20 17:21
@bernhard42 any update?

**Comment by bernhard42** [comment] 2019-04-22 19:07
> @bernhard42 any update?

I tried. At the moment it doesn't even recognize links in the wiki-file.

**Comment by ranebrown** [comment] 2019-04-25 03:41
Can you explain that comment a bit? If I create a link on the index page to `[[file]]` and then go to that new page and run `:VWB` I get a list pointing to the index file. If I create another page `[[second_link]]` and add a link to `[[file]]` on that page then go back to the `file.wiki` page and run `:VWB` again it points to the index page and `second_link.wiki`.

**Comment by ranebrown** [comment] 2019-05-14 11:40
I'm going to close this for now since there hasn't been a response and it works correctly in my testing.

**Comment by ExarchD** [comment] 2019-05-15 13:59
I can confirm that the dev branch isn't working for me on Windows.

**Comment by ranebrown** [comment] 2019-05-16 03:27
@ExarchD Can you try the minimal vimrc steps on the [troubleshooting page](https://github.com/vimwiki/vimwiki/wiki/Troubleshooting#minimal-vimrc).

What version of vim are you using?

**Comment by ExarchD** [comment] 2019-05-16 14:31
nvim v0.3.5

I just tried the minimal setup. Same issue for me. I created a new link, went to that file, tried to create backlink and got:
"No other file links to this file"

**Comment by ranebrown** [comment] 2019-05-16 23:44
Ok, I'm seeing the same thing using nvim on Windows but it is still works with vim 8.1

**Comment by ranebrown** [comment] 2019-05-17 02:48
@ExarchD can you give the change I pushed a try?

**Comment by ranebrown** [comment] 2019-07-12 20:00
Reopen if this still isn't working.

**Closed by ranebrown** 2019-07-12 20:00 UTC
Labels: bug, need-more-info

**Comment by ChenWeird** [comment] 2019-12-31 03:21
I've transfered vimwiki syntax from default to markdown, but haven't changed the links syntax from default `[[Link]]` to markdown `[Link](Link)`.

And now `:VimwikiBacklinks` only recognize the new markdown syntax links, but not the default syntax links.

OS: win 10 pro
gVim version: 8.2 x64

**Comment by ChenWeird** [comment] 2019-12-31 04:34
Transform links syntax of Vimwiki default to Markdown:

```
%s/\[\[\(\([^|]\{1,\}\)|\)\([^]]\{1,\}\)\]\]/[\3](\2)/ge
%s/\[\[\([^]]\{1,\}\)\]\]/[\1](\1)/ge
```

**Comment by lucasdf** [comment] 2020-02-01 17:06
hey @ChenWeird ! Have you managed to fix this by using this regex you provided? what did you change exactly?

**Comment by ChenWeird** [comment] 2020-02-01 18:03
> hey @ChenWeird ! Have you managed to fix this by using this regex you provided? what did you change exactly?

Yes, I have applied the regex. Everything is ok.

**Comment by lucasdf** [comment] 2020-02-01 19:26
Oh, I see. You used the regex to transform Vimwiki link to Markdown link. I would like to use the Vimwiki link style with the Markdown config. The command `VimwikiBacklinks` is working in the master branch with Vimwiki links in a markdown wiki.
