### ISSUE TITLE
No longer able to follow links with dots

### ISSUE THREAD

**Issue by mgarort** [vimwiki/vimwiki#924] opened 2020-06-20 15:47 UTC
OS Ubuntu 18
Vim version: 8.1
Vimwiki version: Stable version 2.5 (obtained from `:VimwikiShowVersion)
Vimwiki native syntax
------------------------------------------------------------------------

Hello,

(First of all, a big thank you to the contributors for maintaining and developing Vimwiki. I started using it for note-taking 3 months ago and it has completely changed the way I work and keep track of things. I absolutely love it.)

My issue is the following: I keep a big archive of notes with Vimwiki. Many of which are related to coding, so the dot `.` is a common character in my note filenames/titles (for instance, I have notes about Python functions and objects such as `os.path` or `sys.stdout`). This used to work just fine with the previous Vimwiki version, but I've just realized that I cannot follow links to notes with dots anymore. I believe this is due to `dev` branch being merged and the release of version 2.5.

Specifically what happens is that, whenever there is a dot `.` in a link, pressing `<CR>` will try to open the corresponding file without the `.wiki` extension, which doesn't exist. For example:
- Let's say I have a note called `Handling paths in Python: os.path.wiki`, and I have a link `[[Handling paths in Python: os.path]]`. Trying to follow the link with `<CR>` will open a new file called `Handling paths in Python: os.path`. 
-  However, if the note is called just `Handling paths in Python.wiki` and the link is `[[Handling paths in Python]]`, it will work fine.

So my question is:
- Is this change in behaviour intended and is it going to stay (if so, I think I may have to write my own basic version of `VimwikiFollowLink` so that my old notes keep working)?, or
- Is this change unexpected and it is going to be reverted?, or
- Actually the behaviour hasn't changed and I must have a rogue config in my `.vimrc`?

Thanks!

**Comment by amnn** [comment] 2020-06-21 17:56
I noticed this after updating recently as well (teach me to run an update when everything was fine).  I tracked the behaviour down to this code:

https://github.com/vimwiki/vimwiki/blob/68e33e37e51a53dbee916d1756b8fef2c2ecfdf5/autoload/vimwiki/base.vim#L235-L238

Which, by using `fnamemodify( ..., ':e')` mistakes a filename with dots in it as having an extension.  This has been around since the initial commit, so isn't what changed recently.  My money is on https://github.com/vimwiki/vimwiki/commit/86cad979e5c53007bb1b0fc6acb13203a8a115a9 being the recent change, which if you, like me, use the markdown format.

**Comment by brennen** [comment] 2020-06-22 18:46
I've noticed this as well on a few pages but hadn't taken the time to track it down.  I use VimWiki syntax, so it's not specific to Markdown.

**Comment by jmcphers** [comment] 2020-06-23 18:36
Also just updated. I use dots for just about all my pages (ending them with the YYYY.MM.DD convention when taking notes) so this has made most of my links not work. :-(

**Comment by dynohub** [comment] 2020-07-21 19:49
I just updated vimwiki and this problem broke a couple dozen links for me. My vimwiki file has links in both the markdown and the vimiwiki links syntax. (Awesome in its inconsistency!) The dots in the filenames break both. My workaround is just to edit my files directly instead of through the wiki links. But... that's not really fun. Do y'all think I should just hold out for a fix? Or go through and rename all my files and their links? (Also... not really fun.)

**Comment by tinmarino** [comment] 2020-07-21 22:13
The best would be to create a Pull Request, if I don't close this in the 2 next days. It seems that it affects many people and it is an horrible bug.

**Comment by tinmarino** [comment] 2020-07-21 23:41
Did 068a26a Fixed some extension REMOVAL (so addition)

If the file has dots in its name, no extension is added because the extension is supposed to be present
Mean if you press enter in `file.with.dot` the extension is dot

I am not sure if the code is good but the tests are showing the expected behavior.

**Comment by mgarort** [comment] 2020-07-22 00:34
Hi @tinmarino , thanks for your message!

I'm not sure if I understand correctly, what is the new change with respect to before [068a26a](https://github.com/vimwiki/vimwiki/commit/068a26acecf0c75ca0ec93711adba85cb86ac12d)? Before, if you tried to follow the link `[[file.with.dot]]`, it opened the file `file.with.dot`, instead of the expected `file.with.dot.wiki`. Maybe this is the new expected behaviour, but it is inconsistent with the previous version and also I don't see where the benefit of this new approach would be, given that files with different extensions can already be linked to with the syntax `[[file:/path/to/file]]`.

**Comment by tinmarino** [comment] 2020-07-22 01:17
> I'm not sure if I understand correctly, what is the new change with respect to before 068a26a?

Sometimes the extension got removed in the markdown case, so finally nothing related to your case ... sorry I realized that little by little.


I do not know if this is the desired behavior because in my `[file.with.dot](file.with.dot.md)`, it does not matter but in you `[[file.with.dot]]` that are 99% wiki files, of course `[[file.with.dot.wiki]]` is verbose.

Your desired behavior seems ok. I'm gonna study that (thanks to @amnn comment) : see when it happened, what it changed.

**Comment by dynohub** [comment] 2020-07-22 14:46
Thanks for tackling this!

**Comment by mgarort** [comment] 2020-08-12 12:21
Hi everyone,

It dawned upon me today that this is probably not a bug, and I've just been terribly obtuse (at least in the native Vimwiki syntax I'm using, don't know about markdown since I don't use that one). Let me explain.

When there is a dot `.` in the note filename, Vimwiki is assuming that such dot marks the filename extension. So:
- If we have a note called `NoteWithoutDots.wiki`, both links `[[NoteWithoutDots.wiki]]` and `[[NoteWithoutDots]]` will work.
- If we have a note called `Note.With.Dots.wiki`, the link `[[Note.With.Dots]]` will not work because Vimwiki will think `.Dots` is the file extension. However, `[[Note.With.Dots.wiki]]` will work perfectly. So we just have to add the suffix `.wiki` to our links and `VimwikiFollowLink` will work as desired.

Now, I think this should actually be the desired behaviour and it is very well designed. Why? Because it gives you the possibility to follow links to other text files with different file extensions. For instance, if I have a tab-separated file `dataset.tsv` and I want to be able to open it from Vimwiki, I can just write a link `[[dataset.tsv]]` and Vimwiki will obediently open it. But if Vimwiki always added the file extension `.wiki` before following the link, then it  would open `dataset.tsv.wiki`, which doesn't exist.

Solution: simply append `.wiki` to your links whenever you have a dot `.`.

If @tinmarino agrees I will close this.

**Comment by tinmarino** [comment] 2020-08-12 12:49
@mgarort : That is the idea. The worth case scenario is a file called `file.wiki.wiki` which may get the wiki removed twice.



You can test this feature removing the `if markdown` of this line: https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/base.vim#L2173

And then setting `let g:vimwiki_markdown_link_ext` in your vimrc.

Before changing the default behavior, tests must be made. It appears that users are the best tests in vimwiki. you can try that locally.

> If @tinmarino agrees I will close this.

I would keep it open: in the best case, user could decide to always strip one `.wiki` if present and append one .wiki when navigating. Actually a file with no extension the conflict with `file.with.dot` also appears with `file_no_dot`. It is just, lot of code (1h dev, 2h tests) for a feature I will never use. If someone want to make a PR ..  :-)  @

**Comment by tinmarino** [comment] 2021-06-09 13:46
Thanks @mgarort  for the clear formalisation in [your comment|https://github.com/vimwiki/vimwiki/issues/924#issuecomment-672837685].
This is in my opinion the best way to handle those file. I've just added a test.

**Closed by tinmarino** 2021-06-09 13:46 UTC
Labels: bug, link, regression
