### ISSUE TITLE
Folding with markdown syntax and a python code block comments is broken

### ISSUE THREAD

**Issue by OliverKnights** [vimwiki/vimwiki#756] opened 2019-10-12 14:48 UTC
Branch: dev          
Revision: ba84981
Date: 2019-08-28 03:51:51 -0600

With the following code using markdown syntax and trying to fold headings, vimwiki interprets the python comments as headers and doesn't fold correctly.

    # Python test

    ``` python
    # python comment
    print("test")
    ```

    ## other heading
    other heading text

I would expect folding on the first line using foldmethod=expr to fold the entire file, but it only folds up until the comment 

Thanks

**Comment by ranebrown** [comment] 2019-10-17 04:33
@OliverKnights can you give the dev branch a try?

Duplicate of #212

**Comment by OliverKnights** [comment] 2019-10-17 11:58
Works perfectly, thanks!

**Comment by ranebrown** [comment] 2019-10-17 12:21
No problem!

**Closed by ranebrown** 2019-10-17 12:21 UTC

**Comment by mellery451** [comment] 2022-06-16 23:40
I have this exact problem in stable version 2.5. Is it possible it regressed for some reason ?
