### ISSUE TITLE
Folding code blocks using markdown syntax folds the entire rest of the file

### ISSUE THREAD

**Issue by maxjmax** [vimwiki/vimwiki#1323] opened 2023-03-30 10:03 UTC
When folding a code-block in markdown (delimited by three backticks), the entire rest of the file is folded.

For example folding

````
# Header

```sql
SELECT blah FROM bleh;
```

# Header two

More text
````

and trying to fold the codeblock will result in

````
# Header

```sql [7]  SELECT blah FROM bleh;```-----------------
````

rather than the expected

````
# Header

+--- 4 lines: ```sql--------------
# Header two

More text
````

Looking at the fold code, the issue seems to be that we are returning a1 when we match rxPreStart, but for markdown rxPreStart and rxPreEnd are both going to be '```', so we return a1 for both the opening and closing delimiters.

```
function! VimwikiFoldLevel(lnum) abort
  let line = getline(a:lnum)

  " Header/section folding...
  if line =~# vimwiki#vars#get_syntaxlocal('rxHeader') && !vimwiki#u#is_codeblock(a:lnum)
    return '>'.vimwiki#u#count_first_sym(line)
  " Code block folding...
  elseif line =~# vimwiki#vars#get_syntaxlocal('rxPreStart')
    return 'a1'
  elseif line =~# vimwiki#vars#get_syntaxlocal('rxPreEnd')
    return 's1'
  else
    return '='
  endif
endfunction
```

I fixed this with a custom fold level method that also checks the previous and next lines, and returns a1 if the previous line is empty, and s1 if the next line is empty, and this is working for me.

```
function! VimwikiFoldLevelMD(lnum) abort
  let line = getline(a:lnum)
  " previously it would always increment when it saw a ```, so we never left the code block.
  let prevline = getline(v:lnum - 1)
  let nextline = getline(v:lnum + 1)

  " Header/section folding...
  if line =~ vimwiki#vars#get_syntaxlocal('rxHeader') && !vimwiki#u#is_codeblock(a:lnum)
    return '>'.vimwiki#u#count_first_sym(line)
  " Code block folding...assume empty line before and after
  elseif line =~# vimwiki#vars#get_syntaxlocal('rxPreStart') && prevline =~ '^\s*$'
    return 'a1'
  elseif line =~# vimwiki#vars#get_syntaxlocal('rxPreEnd') && nextline =~ '^\s*$'
    return 's1'
  else
    return '='
  endif
endfunction
```

but I could not find an existing issue for this, so was unsure if I was missing something, since I would expect it to affect quite a few people, unless most people use vim-markdown's folding in this situation instead? Happy to attempt a fix if this is a genuine issue and the approach above looks valid.

vimwiki settings

```
	\ 'automatic_nested_syntaxes': 1, 
	\ 'syntax': 'markdown', 
	\ 'ext': '.md'

let g:vimwiki_folding = 'expr'

```

vimwiki version

```
Version: 2022.12.02
Os: Linux
Vim: 900
Branch: dev
Revision: fea8bee
Date: 2022-12-04 21:25:52 -0700
```

**Comment by brennen** [comment] 2023-04-05 00:23
> but I could not find an existing issue for this, so was unsure if I was missing something, since I would expect it to affect quite a few people, unless most people use vim-markdown's folding in this situation instead? Happy to attempt a fix if this is a genuine issue and the approach above looks valid.

I guess it's possible it just hasn't come up all that often.

I'd be happy to review a fix. I'm wondering if checking on next/previous line as blank might be kind of brittle, though. Would be nice if the function just knew it was already in a fold somehow... 'course I haven't looked at the implementation here at all to really have an opinion.

**Comment by tinmarino** [comment] 2023-06-22 21:58
Hi @maxjmax, I can reproduce your issue. You are right, VimWiki can make confusion on open vs closing regexp.

I tried to maintain an internal state bu depending on where highlighting starts, the fold gets corrupted differently. Your solution to lookaround is the only one so far.

This has not been reported before, I guess because people do not fold a lot code blocks.

Here my current configuration

```vim
echo append("$", vimwiki#vars#get_syntaxlocal('rxPreEnd'))
echo append("$", vimwiki#vars#get_syntaxlocal('rxPreStart'))

^\s*\%(`\{3,}\|\~\{3,}\)              <--- Start
^\s*\%(`\{3,}\|\~\{3,}\)\s*$          <--- End
```

**Comment by tinmarino** [comment] 2023-06-22 22:09
> Would be nice if the function just knew it was already in a fold somehow... (@brennen)

I definitely agree with that. I tried the implementation below but folding gets corrupted while typing.

To fix the fold, then one has to `:e`  and `zx`  (z like fold and x like recalculate).

```diff

+let s:vimwiki_fold_block_open = 0
+
 " Get fold level for 1. line number
 function! VimwikiFoldLevel(lnum) abort
   let line = getline(a:lnum)
@@ -194,9 +196,11 @@ function! VimwikiFoldLevel(lnum) abort
   if line =~# vimwiki#vars#get_syntaxlocal('rxHeader') && !vimwiki#u#is_codeblock(a:lnum)
     return '>'.vimwiki#u#count_first_sym(line)
   " Code block folding...
-  elseif line =~# vimwiki#vars#get_syntaxlocal('rxPreStart')
+  elseif line =~# vimwiki#vars#get_syntaxlocal('rxPreStart') && s:vimwiki_fold_block_open == 0
+    let s:vimwiki_fold_block_open = 1
     return 'a1'
   elseif line =~# vimwiki#vars#get_syntaxlocal('rxPreEnd')
+    let s:vimwiki_fold_block_open = 0
     return 's1'
   else
     return '='
```

**Comment by tinmarino** [comment] 2023-06-22 22:23
I think @maxjmax is the best (only) solution: check for above and below.

* [vim-markdown-folding](https://github.com/masukomi/vim-markdown-folding/blob/6518dce7a82f6283a482ee60f8f38b88f5c0b54a/after/ftplugin/markdown/folding.vim) uses the same regex
* [Github markdown spec](https://github.github.com/gfm/#fenced-code-blocks) do not help for discriminating opening or closing delimiters.
* I always prefix my code block by an empty line (but I also try to always specify the language name).
* It also has the advantage to be safe in the sense that if we are in an unknown situation (not opening, nor closing), the foldlevel is unchanged.

It that OK (acceptable) for you @brennen? May you please create a PR @maxjmax?

**Comment by tinmarino** [comment] 2023-10-31 15:10
It seems to work fine for me now

```
-     1 # Header
|     2
|-    3 ```sql
||    4 SELECT blah FROM bleh;
||-   5 ```
|||   6
-     7 # Header two
|     8
|     9 More text
``

**Comment by tinmarino** [comment] 2023-10-31 16:13
Fixed as proposed by @maxjmax and accepted by @brennen.

**Closed by tinmarino** 2023-10-31 16:13 UTC
Labels: markdown, syntax, folding
