### ISSUE TITLE
Q: How can I make vimwiki convert spaces (in wikilinks) to dashes while creating files?

### ISSUE THREAD

**Issue by praddy** [vimwiki/vimwiki#48] opened 2014-05-12 11:47 UTC
I see that vimwiki_badsyms doesn't exist anymore in 2.1. Is there any other way?

**Comment by PeterHolloway** [comment] 2016-04-20 11:58
This would be very useful. Having to use `[[foo_bar|Foo Bar]]` to prevent spaces in filenames is a pain

**Comment by johnmarcampbell** [comment] 2017-10-24 01:34
I'm closing this, as the Issue is ~3.5 years old and it appears that the answer is a simple no.

**Closed by johnmarcampbell** 2017-10-24 01:34 UTC

**Comment by josswright** [comment] 2017-11-04 23:04
I just returned to using vimwiki after having experimented with it some time ago, and found this issue whilst trying to resolve the spaces issue myself. Coincidentally, it seems to have just been closed. Was vimwiki_badsyms problematic somehow? I'd also be very much in favour of this feature.
