### ISSUE TITLE
iabbrev not work in vimwiki, but work in vim

### ISSUE THREAD

**Issue by Gary-Chow** [vimwiki/vimwiki#415] opened 2017-12-01 02:28 UTC
Dear all,

Thank you very much for the amazing plugin - vimwiki.

Problems:
Recently, I want to use "iabbrev" in vimwiki, but it works in vim, not working in vimwiki.

In Vim:        sc<space>  -->  solar cells
In Vimwiki:  sc<space>  -->  sc<space>

software version:
I am using vim7.4, installing vimwiki by vundle with "vimwiki/vimwiki"

Regards,
Gary

**Comment by Nudin** [comment] 2017-12-04 15:46
I can't reproduce this. Where have you defined you iabbrev's? Can you try :iabbrev when having vimwiki opened to see if it is (still) defined?

**Comment by carny** [comment] 2018-06-07 05:03
I'm having the same issue. I have a single iabbrev defined in my `.vimrc` file.

```iabbrev dts strftime("%Y-%m-%d %H:%M")```

I'm using vim 8.0.1283.

**Comment by carny** [comment] 2018-06-07 05:13
There seems to be a difference where vim registers the abbreviation after a return carriage and will not register the abbreviation after a space. Vimwiki is the opposite where it is registering the abbreviation after a space character and not after a return. Not sure why the two are different.

**Comment by ranebrown** [comment] 2019-04-14 04:46
The standard vim behavior expands the abbreviation after hitting space, enter, or entering punctuation. Since vimwiki remaps `<CR>` the enter case is disabled. This can be fixed by adding `<C-]` to the vimwiki mapping to forcibly expand the abbreviation.
```vim
if has('patch-7.3.489')
  inoremap <CR> <C-]><Esc>:VimwikiReturn 1 5<CR>
endif
```

`C-]` didn't work in a key mapping prior to patch 7.3.489.

**Closed** 2019-05-24 04:07 UTC
Labels: easy, work-around-exists
