### ISSUE TITLE
In markdown syntax, italic and emphasis symbols are incorrect.

### ISSUE THREAD

**Issue by newptcai** [vimwiki/vimwiki#318] opened 2017-03-25 22:38 UTC
In MarkDown, one * or _ is used for italic. And double ** or double __ are for emphasis.

**Comment by Gekazoid** [comment] 2017-03-27 14:15
Same story with links, vimwiki uses
`[[This is a link source|Description of the link]]`
instead of
`[Description of the link](This is a link source)`
Markdown syntax ~broken at all~ doesn't fit any widespread markdown dialect ([pure markdown](http://daringfireball.net/projects/markdown/syntax), [github](https://guides.github.com/features/mastering-markdown/), [pandoc's parkdown](http://pandoc.org/MANUAL.html#pandocs-markdown))
Statement that vimwiki has native support of markdown is not true. No one markdown editor or previewer can't understand markdown dialect of this plugin.
At the present stage, using markdown as default format in vimwiki is pointless.

**Comment by pjf** [comment] 2017-03-31 02:42
Trying to do some triage and make sense of this ticket, I think I can summarise the following (with markdown mode enabled):

- vimwiki treats `*italic*` and `**bold**` differently to `_italic_` and `__bold__`. All of them get visually highlighted, but they get _differently_ highlighted depending whether asterisks or underscores are used. The highlighting should be the same.
- vimwiki handles `[markdown links](example.md)` completely fine in markdown mode, including displaying them correctly, and handing them off to a browser when selected. However when it *generates* links (eg: with `\w\i` to reindex the diary page) it defaults to its `[[example|native links]]` style.
- When new links are generated, they don't include the file extension, so we get a link to `example` rather than `example.md` or `example.wiki`.

Thus the desired changes requested in this ticket are (with markdown mode enabled):

- [ ] Have `_italic_` and `*italic*` work the same.
- [ ] Have `__bold__` and `**bold**` work the same.
- [ ] Have autogenerated links be in `[markdown syntax](example)`.
- [ ] Have autogenerated links include the file extension.

On a personal note I run all my vimwiki instances in markdown mode, and have been finding it far from "pointless". Everything I've done has worked as expected, and I *really* like being able to use `[[Simple Links]]` rather than `[Complex Links](Complex Links.md)`, even though they're not strictly markdown. I think it would be a misfeature if markdown mode prevented the generation of simple links.

>  Statement that vimwiki has native support of markdown is not true. No one markdown editor or previewer can't understand markdown dialect generated by this plugin.

I think it would be correct to say that vimwiki *understands* markdown natively, but doesn't guarantee to always produce markdown when generating links.

**Comment by ranebrown** [comment] 2018-07-23 19:55
It looks like the auto-generated links are now created correctly for markdown (such as TOC) but the bold and italic issue has not been fixed. Is this still being worked on?

Here is what I am currently seeing:
`**bold**` shows as \***bold**\*
`__bold__` shows as \_*bold*\_
`_italic_` shows as _italic_
`*italic*` shows as **italic**

**Comment by Wolfereign** [comment] 2018-08-16 16:05
To add to this strikethrough just highlights in purple and escape backslash doesn't work.  

~~~Strike Through~~~ doesn't work
\*words\* shows as \words\

Also, horizontal lines and block quotes doe not seem to work at all.  Don't know if that's a bug or just not implemented.

**Comment by lucidstack** [comment] 2019-02-09 13:26
Looks like this is still an unresolved issue. As a workaround, create a `$(N)VIM_FOLDER/after/ftplugin/vimwiki.vim` file, with:

```vim
" text: **strong** or __strong__
let g:vimwiki_syntax_variables.markdown.rxBold = '\%(^\|\s\|[[:punct:]]\)\@<='.
      \'[*_][*_]'.
      \'\%([^*`[:space:]][^*`]*[^*`[:space:]]\|[^*`[:space:]]\)'.
      \'[*_][*_]'.
      \'\%([[:punct:]]\|\s\|$\)\@='
let g:vimwiki_syntax_variables.markdown.char_bold = '__\|\*\*'

" text: *italic* or _italic_
let g:vimwiki_syntax_variables.markdown.rxItalic = '\%(^\|\s\|[[:punct:]]\)\@<='.
      \'[*_][^*_]'.
      \'\%([^_`[:space:]][^_`]*[^_`[:space:]]\|[^*`[:space:]]\)'.
      \'[*_][^*_]'.
      \'\%([[:punct:]]\|\s\|$\)\@='
let g:vimwiki_syntax_variables.markdown.char_italic = '_\|\*'

" text: **_bold italic_** or _**italic bold**_
let g:vimwiki_syntax_variables.markdown.rxBoldItalic = '\%(^\|\s\|[[:punct:]]\)\@<='.
      \'\*\*_'.
      \'\%([^*_`[:space:]][^*_`]*[^*_`[:space:]]\|[^*_`[:space:]]\)'.
      \'_\*\*'.
      \'\%([[:punct:]]\|\s\|$\)\@='
let g:vimwiki_syntax_variables.markdown.char_bolditalic = '\*\*_'

let g:vimwiki_syntax_variables.markdown.rxItalicBold = '\%(^\|\s\|[[:punct:]]\)\@<='.
      \'_\*\*'.
      \'\%([^*_`[:space:]][^*_`]*[^*_`[:space:]]\|[^*_`[:space:]]\)'.
      \'\*\*_'.
      \'\%([[:punct:]]\|\s\|$\)\@='
let g:vimwiki_syntax_variables.markdown.char_italicbold = '_\*\*'

" Bonus: vimwiki only has cterm=bold by default. ¯\_(ツ)_/¯
hi VimwikiBoldItalic term=bold cterm=bold,italic gui=bold,italic
```

This will give you the expected behaviour: `**strong**`, `*italic*`, `**_strong italic_**` and `_**italic strong**_`. It's not perfect, as you can't nest parts of italic/bold text inside bold/italic, but it should do the trick! :slightly_smiling_face:

**Comment by ranebrown** [comment] 2019-03-15 12:44
This has been fixed on the `dev` branch which should be merged into `master` soon. Stay tuned.

**Comment by bewuethr** [comment] 2019-03-15 13:54
@ranebrown Thank you, this was bothering me for a while! Nitpick: `_**bolditalic**_` and similar combinations still don't work.

**Comment by ranebrown** [comment] 2019-03-15 14:22
@bewuethr Take a look at the updated documentation. I changed those to `***bold_italic***` and `___italic_bold___` :) Let me know if that works as expected.

**Comment by ranebrown** [comment] 2019-03-15 14:25
I based this decision of the following line in the [CommonMark spec](https://spec.commonmark.org/0.28/#emphasis-and-strong-emphasis) in case you are curious:

> The original Markdown.pl test suite makes it clear that triple *** and ___ delimiters can be used for strong emphasis

**Comment by bewuethr** [comment] 2019-03-15 14:41
Yes, the behaviour for `***foo***` and `___foo___` is as expected, renders bold and italic. But the rendering of mixed delimiters seems to contradict what [example 438](https://spec.commonmark.org/0.28/#example-438) and [example 440](https://spec.commonmark.org/0.28/#example-440) show:

| Input | Spec | Vimwiki rendering |
|-|-|-|
|`_*foo*_`|*`foo`*|*`_foo_`*|
|`*_foo_*`|*`foo`*|*`*foo*`*|

No big deal, really – thanks for the fix in the first place!

**Comment by ranebrown** [comment] 2019-03-15 14:47
Yeah, there are a ton of possible cases when you look at the spec. It would be way too difficult to cover them all but hopefully this implementation works for most people.

Of course! This one was bothering me for a while too.

**Comment by ranebrown** [comment] 2019-03-27 03:10
I'm going to close this since the fix is in `dev` and slated for the v2.5 release (#638)

**Closed by ranebrown** 2019-03-27 03:10 UTC

**Comment by davidsierradz** [comment] 2019-05-13 00:20
I think conceal is broken when using backticks inside bold or italic sentences:

Input | Spec | Vimwiki rendering
-- | -- | --
\*\*hello \`world\`\*\*| **hello `world`** | \*\*hello `world`\*\*
\*hello \`world\`\*| *hello `world`* | \*hello `world`\*

**Comment by ranebrown** [comment] 2019-05-13 03:20
@davidsierradz Please create a new issue.
