### ISSUE TITLE
Default wiki is incorrect despite specifying 'path' when the plugin is loaded before the global variable is set

### ISSUE THREAD

**Issue by thorlucas** [vimwiki/vimwiki#1072] opened 2020-12-27 09:02 UTC
I'm specifying one and only one Wiki in my `g:vimwiki_list`:

```lua
vim.cmd [[packadd vimwiki]]

vim.g.vimwiki_list = {
	{
		path = '~/Dropbox/Wiki/',
		path_html = '~/Dropbox/Wiki_HTML/',
		template_path = '~/Dropbox/Wiki/Templates/',
		template_default = 'default',
		syntax = 'markdown',
		ext = '.md',
		custom_wiki2html = '~/.local/share/nvim/scripts/wiki2html.sh',
	}
}
```

I can confirm by typing `:echo g:vimwiki_list`:

```vimscript
[{'template_default': 'default', 'custom_wiki2html': '~/.local/share/nvim/scripts/wiki2html.sh', 'template_path': '~/Dropbox/Wiki/Templates/', 'path': '~/Dropbox/Wiki/', 'path_html': '~/Dropbox/Wiki_HTML/', 'ext': '.md', 'syntax': 'markdown'}]
```

`:VimwikiShowVersion`:

```
Os: Mac
Vim: 800
Branch: dev
Revision: e4fc0ca
Date: 2020-12-22 20:25:56 -0300
```

When I am *on* the wiki, the correct wiki is opened.

I have also confirmed that it is not due to the order in which the settings are specified when translated from lua to vim, by only leaving the path:

```vimscript
" :echo g:vimwiki_list
[{'path': '~/Dropbox/Wiki/'}]
```

**However, when `[[packadd vimwiki]]` is called after, it works properly**

Therefore, if the plugin is loaded before g:vimwiki_list is set, the default wiki will be wrong.

**Comment by thecliguy** [comment] 2021-01-02 17:24
When VimWiki is initially loaded it reads `g:vimwiki_list` and populates `vimwiki_wikilocal_vars`. If `g:vimwiki_list` is not present then a wiki is registered by populating `vimwiki_wikilocal_vars` with default values.

So once VimiWiki is loaded, you should check the value of `vimwiki_wikilocal_vars` (not the value of `g:vimwiki_list`):
```
:echo vimwiki_wikilocal_vars
```

Please read of issue #935 which I believe to be essentially the same predicament as yours. In the answer provided by @tinmarino the exact sequence of events for `vimwiki_wikilocal_vars` population is mapped out. The answer also contains [a reference to the VimWiki documentation](https://github.com/vimwiki/vimwiki/issues/935#issuecomment-661647681) that acknowledges that settings should be set before Vimwiki loads.

So I believe that the behavior you're seeing is not a bug or an oversight, it's how VimWiki is designed to operate.

I hope this helps clear things up. Please provide feedback or close the issue if I have explained things satisfactorily.

**Comment by tinmarino** [comment] 2021-01-02 18:53
In short customize before packadd or use the new `VimvikiVar`

**Closed by tinmarino** 2021-01-02 18:53 UTC
