### ISSUE TITLE
Errors when switching to Markdown format

### ISSUE THREAD

**Issue by trevorfoxsoft** [vimwiki/vimwiki#1307] opened 2023-02-26 09:07 UTC
I have a fresh Neovim installation and have installed vimwiki, both from Nix packages on NixOS. I want to use Markdown, so in my init.lua, I have this:

```
vim.cmd([[
  set nocompatible
  filetype plugin on
  syntax on
  let g:vimwiki_list = [{'path': '$HOME/notes/, 'syntax': 'markdown', 'ext': '.md'})
]])
```

When hitting `<leader>ww`, I get the error:

```
Error detected while processing function vimwiki#base#goto_index[33]..vimwiki#base#edit_file[26]..function vimwiki#b
ase#goto_index[33]..vimwiki#base#edit_file[18]..BufReadPost Autocommands for "*.md"..function <SNR>37_setup_new_wiki
_buffer[19]..vimwiki#u#ft_set[6]..FileType Autocommands for "*"..Syntax Autocommands for "*"..function <SNR>11_SynSe
t[25]..script /nix/store/ivnr4bzbpq2p9j6hzb1f79ifsspp4089-vimplugin-vimwiki-2022-03-10/syntax/vimwiki.vim[460]..func
tion vimwiki#u#reload_regexes_custom[1]..script /home/tsv/.local/share/nvim/site/pack/packer/start/vimwiki/syntax/vi
mwiki_markdown_custom.vim[107]..function vimwiki#vars#get_global:
line    1:
E716: Key not present in Dictionary: "schemes_local"
```

The wiki index page then seems to load fine however.

If I hit Return on a word to create a link, I get 
```
Error detected while processing function vimwiki#base#follow_link[89]..vimwiki#base#normalize_link:       
line    3:
E118: Too many arguments for function: vimwiki#markdown_base#normalize_link
```
and the link is not created. I can manually create links using square brackets and these work fine.

Vimwiki is stable version 2.5.

**Comment by brennen** [comment] 2023-03-07 16:22
How is the plugin installation itself managed?

**Comment by brennen** [comment] 2023-03-07 16:23
> Vimwiki is stable version 2.5.

Also you may want to try installing the latest release: https://github.com/vimwiki/vimwiki/releases/tag/v2022.12.02

**Comment by mhhf** [comment] 2023-03-07 19:43
I'm having the same error running neovim v0.8.1. Installed vimwiki with packer and tried the dev branch and the release you are referring to, but both lead to the same error

**Comment by brennen** [comment] 2023-03-07 19:54
I think this might be #1288 (and I suspect documented on other issues, although I don't have time to go looking at the moment).

**Comment by mhhf** [comment] 2023-03-07 20:27
Thanks! I reinstalled vimwiki without packer and it works without issues!

**Comment by brennen** [comment] 2023-03-07 20:49
Cool; I'm going to close this as a duplicate of #1288. Further investigation can happen there.

**Closed by brennen** 2023-03-07 20:49 UTC
Labels: markdown, neovim

**Comment by trevorfoxsoft** [comment] 2023-03-09 20:10
This has resolved itself with an upgrade (which I did by switching to NixOS unstable). Thanks.
