### ISSUE TITLE
Using vim-pandoc folding with vimwiki

### ISSUE THREAD

**Issue by abers** [vimwiki/vimwiki#461] opened 2018-03-21 12:21 UTC
I am having difficulty setting up vimwiki so that md files in vimwiki folder locations use the vim-pandoc plugin for folding. I have vimwiki setup to use markdown syntax and file extensions, which seems to prevent the folding from vim-pandoc being used. Disabling temporary wiki's `let g:vimwiki_global_ext= 0`, fixes this for markdown files outside of vimwiki folder locations. From what I gathered from the documentation, `let g:vimwiki_folding='custom'` should also leave the folding for files in vimiwiki folder locations to settings from another plugin. However, even with this in my .vimrc vim-pandoc folding does not work within vimwiki.

**Comment by kwrobert** [comment] 2018-04-29 15:29
I think this is because vimwiki forcibly sets the filetype to just strictly 'vimwiki' whenever it gets initialized. The vim-pandoc plugin requires the filetype to have 'pandoc' somewhere within it to initialize, so even though you've set the vimwiki_folding='custom' the vim-pandoc plugin never intializes because you don't have the correct filetype when editing your wiki files. 

The only way I've found to fix this is by modifying the plugin sources by hand, because the 'vimwiki' filetype is hardcoded in a few places there. Try grepping for 'filetype' in the vimwiki plugin sources, and setting the filetype to 'vimwiki.pandoc' everywhere it seems appropriate. This has worked for me so far, but I think I'm going to open another issue request and enhancement to support multiple filetypes

**Comment by shiro** [comment] 2018-09-10 08:04
Is there any better way to fix this other than forking atm?
Both vimwiki and pandoc are really awesome, so it would be nice to be able to use them both on md files.

**Comment by peterhoejlundandersen** [comment] 2018-09-14 18:51
@kwrobert - how did you get it to work? 
I've forked and changed it two places in the plugin > vimwiki.vim file from `vimwiki` to `vimwiki.markdown` - but still only vimwiki is set. 
Can you guide me?

**Comment by peterhoejlundandersen** [comment] 2018-09-14 19:02
I just added this: `au FileType vimwiki set filetype=vimwiki.markdown` to my .vimrc and now it is working. PreVim in VimWiki file!

**Comment by peterhoejlundandersen** [comment] 2018-09-15 09:44
I have set this op, so i can use markdown snippets and markdown preview with VimWiki. 
It's working as it should: 

`au FileType vimwiki set filetype=vimwiki.markdown`

**Comment by shiro** [comment] 2018-10-01 12:08
Does not seem to work.
As soon as I add `au FileType vimwiki set filetype=vimwiki.markdown` (enabling vimwiki everywhere) wimwiki seems to take over and I cannot use pandoc anymore. (folding, keybinds, etc.)

Whether I load pandoc before or after vimwiki does not seem to matter, neither does overriding the filetype. (using plug)

**Comment by Hipomenes** [comment] 2018-10-07 16:53
I'm in the same situation. Would love to use vimwiki and vim-pandoc, but they don't seem to interact very well.

**Comment by redapemusic35** [comment] 2019-02-13 15:45
This worked for me. I was having the same problem

```
set foldenable

let g:pandoc#filetypes#handled = ["pandoc", "markdown"]
let g:pandoc#filetypes#pandoc_markdown = 0
let g:pandoc#folding#mode = ["syntax"]
let g:pandoc#modules#enabled = ["formatting", "folding"]
let g:pandoc#formatting#mode = "h"

let g:vimwiki_folding='expr'
au FileType vimwiki set filetype=vimwiki.markdown
```

**Comment by shiro** [comment] 2019-03-18 08:58
> This worked for me. I was having the same problem
> 
> ```
> set foldenable
> 
> let g:pandoc#filetypes#handled = ["pandoc", "markdown"]
> let g:pandoc#filetypes#pandoc_markdown = 0
> let g:pandoc#folding#mode = ["syntax"]
> let g:pandoc#modules#enabled = ["formatting", "folding"]
> let g:pandoc#formatting#mode = "h"
> 
> let g:vimwiki_folding='expr'
> au FileType vimwiki set filetype=vimwiki.markdown
> ```

Yep, that did it!
Should we consider this a solution or a hack? Not sure about it...

**Comment by shiro** [comment] 2019-03-18 18:51
Ok, apparently the highlighting and folding were only working inside of wikis (but the highlighting behaviour also occurs with only vimwiki as well).

With the following config everything works globally and some pandoc modules can be added as needed. 

```
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'

let g:pandoc#folding#fold_yaml = 1
let g:pandoc#folding#fold_fenced_codeblocks = 1
let g:pandoc#filetypes#handled = ["pandoc", "markdown"]
let g:pandoc#filetypes#pandoc_markdown = 0
let g:pandoc#folding#mode = ["syntax"]
let g:pandoc#modules#enabled = ["formatting", "folding", "toc"]
let g:pandoc#formatting#mode = "h"


" vimwiki

Plug 'vimwiki/vimwiki'

" enable global highlighting
let g:vimwiki_ext2syntax = {'.md': 'markdown'}
let g:vimwiki_folding='expr'

au FileType vimwiki set filetype=vimwiki.markdown
```

**Comment by abers** [comment] 2019-03-19 21:37
I am slightly confused by the proposed solution. Doesn't `let g:pandoc#filetypes#pandoc_markdown = 0` stop vim-pandoc from working with markdown files? Adding the above to my .vimrc results in markdown files no longer using the vim-pandoc-syntax and folding stops working in markdown files. 

I've experimented with various setups for vimwiki and vim-pandoc and seem to keep ending up in situation where I either have folding working in markdown files outside of vimwiki but foldings in vimwiki not working or have vimwiki folding working but not for markdown files outside of vimwiki. At the moment I have it where folding works for markdown files outside of vimwiki and for some bizarre reason folding within vimwiki only works for certain files. For example, when in the index for any wiki it claims 'No fold found' but if I navigate to another page folding will work for around half the pages. No idea why.

Just wish vimwiki allowed setting different FileTypes for different wikis, as I could then have my organisational wiki as vimwiki.markdown and my academic wiki as markdown.pandoc.

**Comment by redapemusic35** [comment] 2019-03-19 21:47
I committed out `let g:pandoc#modules#enabled = ["formatting", "folding", "toc"]
let g:pandoc#formatting#mode = "h"`

which seemed to help. I now have folding enabled but syntax varies for some reason. If it bothers me too much, the difference in syntax, I can change it on the fly with :setfiletype pandoc or :setfiletype markdown. It is not the best but other then highlighting, I have not noticed a difference.

**Comment by abers** [comment] 2019-03-22 12:37
Update: I have now tried the settings detailed in my previous post across three of my devices and all seems to be working well. Folding works in all new vimwiki files and can be fixed on older files in the majority of cases by running `:set filetype=pandoc` once per file. There are 2-3 files which for whatever reason the folding refuses to work still. Even deleting the files and recreating them doesn't fix the problem, but adding the same content to a new file with a different name works.

**Comment by ranebrown** [comment] 2019-04-12 13:55
Can any interested parties test the changes I made to support multiple filetypes on this [branch](https://github.com/vimwiki/vimwiki/tree/multi_ft)?

I tested using these settings and didn't see any issues:
```vim
let g:vimwiki_filetypes = ['markdown']
let g:vimwiki_folding = 'custom'
let g:pandoc#folding#mode = 'stacked'
let g:pandoc#modules#enabled = ['folding', 'command']
```

@Nudin @hq6 What are your thoughts on merging this change into `dev`? I didn't create a pull request since I'm not sure it is something we want to add in permanently since the option has the potential to break the internal workings of vimwiki. I added a warning in the documentation but that might not be sufficient.

**Comment by ranebrown** [comment] 2019-04-12 14:07
Another thing to note: I tried using third party markdown syntax highlighting instead of vimwiki's syntax highlighting as mentioned in #364 and it seems to work without breaking vimwiki's functionality.

**Comment by hq6** [comment] 2019-04-12 18:19
@ranebrown, I think this option is likely to encourage more new interactions with other plug-ins, and we should think carefully about whether that is desirable. Strange behaviors caused by  interactions between different plug-ins are generally harder to debug. 

My first thought is that this could be a documented patch that people can use and not a proper option of Vimwiki (this discourages casual usage causing breakage).

**Comment by ranebrown** [comment] 2019-04-27 12:58
Doesn't seem like there has been further interest in this and there are a couple of workarounds including the experimental branch.

**Closed by ranebrown** 2019-04-27 12:58 UTC
Labels: 3rd-party

**Comment by yaohunzhanyue** [comment] 2020-04-05 03:40
@ranebrown How to set multiple filetypes?
