### ISSUE TITLE
Make auto_export asynchron

### ISSUE THREAD

**Issue by 23tux** [vimwiki/vimwiki#335] opened 2017-04-19 07:44 UTC
The `auto_export` config key is pretty useful, but when I have a very long page, it always takes a couple of pretty annoying seconds to save, and this drives me crazy.

So I was wondering if it's possible to run it asynchron? Or is it possible to trigger the `Vimwiki2HTML` command (or even `VimwikiAll2HTML`) outside of vim? I could think of a file watcher that runs a certain command when something has changed.

**Comment by ranebrown** [comment] 2019-04-06 19:57
This should be possible with Vim 8+. I'm closing as a duplicate of #546 but I think it is something we will be adding.

**Closed by ranebrown** 2019-04-06 19:57 UTC
Labels: enhancement
