### ISSUE TITLE
TOC generator seems to get confused by anchors with the same name

### ISSUE THREAD

**Issue by sdondley** [vimwiki/vimwiki#1205] opened 2022-01-30 08:54 UTC
Prior to submitting a new issue make sure to complete these steps:

- [x ] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [ x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x ] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x ] Include the output of `:VimwikiShowVersion`.

Os: Mac
Vim: 800
Branch: dev
Revision: 4d7a4da
Date: 2021-12-19 00:49:16 -0300

My wiki page has the following:

```
# On This Page

- [Decoding the Gurus](#decoding-the-gurus)
- [Links](#links)                                                                         # THIS WORKS
- [What is it?](#what-is-it)
- [Hosts](#hosts)
    - [Matt Browne](#matt-browne)
        - [Links](#links-2)                                                              # THIS GOES TO WRONG "LINKS"
    - [Chris Kavnaugh](#chris-kavnaugh)
        - [Links](#links-3)                                                              # THIS GOES NOWHERE
- [What do they talk about?](#what-do-they-talk-about)
        - [Highlights of Show](#highlights-of-show)

# Decoding the Gurus

# Links

[Podcast home page](https://decoding-the-gurus.captivate.fm)
[Reddit page](https://www.reddit.com/r/DecodingTheGurus/)
[Unofficial Discord Server](https://discord.gg/z3krx3CX)


# What is it?
* It's primarily a podcast
* Started in late 2020

# Hosts
* Hosts are two researcher working in academia as professors

## Matt Browne
* psychologist
    * currently specializing in research about gambling addictions and public policy 

### Links
* [Twitter](https://twitter.com/arthurcdent)

## Chris Kavnaugh
* cultural anthropologist 
    * researches ritualistic practices

### Links
* [Twitter](https://twitter.com/C_Kavanagh)

# What do they talk about?
* Analyze popular figures in media who have acquired large followings with their sweeping worldviews
    * hosts refer to them as gurus 
    * Mostly cover controversial individuals who promulgate psuedoscience and misinformation 
    * Will occasionally cover individuals who have positive impac5
        * Carl Sagan 
    * Also sometimes interview experts on specific topics
* Frequent targets
    * Sam Harris
    * Bret Weinstein
    * Jordan Peterson
    * Joe Rogan
    * Eric Weinstein
* Help audience members identify fake experts and false arguments and generally improve their ability to think critically about information

### Highlights of Show
* interview with Sam Harris
    * Came on the rebut Chris and Matt 

...more soon
```

The first "Links" anchor in the TOC to "Links" works. The second "Links" anchor in the TOC goes to the third "Links" on the page instead of the 2nd. The third "Links" anchor does nothing when clicked.

**Comment by sdondley** [comment] 2022-02-01 13:53
OK, I just discovered this only happens with the content after it is output to html. I use vimwiki_markdown gem. So the problem is almost certainly there. Keeping this open in case I'm wrong.

**Comment by patrickdavey** [comment] 2022-02-06 20:35
As I mentioned in the other issue -> https://github.com/patrickdavey/vimwiki_markdown/issues/39#issuecomment-1027451228 I think the issue is actually with the form of the input html, and not an issue with `vimwiki` or the `vimwiki_markdown` gem. Either which way, this issue should be closed as it's definitely not an issue with vimwiki itself.

**Closed** 2022-03-06 22:00 UTC
Labels: link, table-of-contents
