### ISSUE TITLE
[Question] Why auto add # on the first line when save file

### ISSUE THREAD

**Issue by xyegithub** [vimwiki/vimwiki#1222] opened 2022-04-07 09:00 UTC
My config:
```vim
let g:vimwiki_list = [{'path': '~/mynote/',
            \ 'syntax': 'markdown', 'ext': '.md', 'auto_toc': 0, 'auto_tags': 0, 'auto_generate_links': 0, 'auto_generate_tags': 0}]
let g:vimwiki_autowriteall=0```

After install vimwiki, an `#` is auto added to the first line, every time I save the markdown file.
I wonder how to disable this. I tried to set `auto_toc': 0, 'auto_tags': 0, 'auto_generate_links': 0, 'auto_generate_tags': 0`. However, none of them are useful.

**Comment by brennen** [comment] 2022-05-22 17:45
Can you post the output of `:VimwikiShowVersion` and `:VimwikiVar auto_header`?

**Comment by tinmarino** [comment] 2023-03-17 07:03
Closing <= cannot reproduce <= more info need

**Closed by tinmarino** 2023-03-17 07:03 UTC
Labels: bug, need-more-info, markdown
