### ISSUE TITLE
On creating a link: 'Ð' char appended

### ISSUE THREAD

**Issue by artkpv** [vimwiki/vimwiki#1042] opened 2020-10-26 07:39 UTC
Hi! How can I fix this issue? Whenever I create a link by pressing Enter it replaces last char with 'Ð' and adds <b8> at the end if I use Cyrillic symbols.

Example / steps to reproduce:

1) Text:
```
     инкубатор_книги
```
2) Press `vE<Enter>`
3) Result:
```
    [инкубатор_книгÐ](инкубатор_книгÐ)� 
```

Environment:

- `dev` branch
- Syntax: "markdown". My vimrc:
```
let g:vimwiki_use_mouse = 1

let g:vimwiki_folding = 'expr'
let g:vimwiki_toc_header = 'Содержание'
let g:vimwiki_auto_chdir = 1
let g:vimwiki_diary_months = {
      \ 1: 'Январь', 2: 'Февраль', 3: 'Март',
      \ 4: 'Апрель', 5: 'Май', 6: 'Июнь',
      \ 7: 'Июль', 8: 'Август', 9: 'Сентябрь',
      \ 10: 'Октябрь', 11: 'Ноябрь', 12: 'Декабрь'
      \ }

let g:vimwiki_global_ext = 0
let g:vimwiki_list = [ {
            \ 'path': '~/mydir/notes/', 
            \ 'path_html': '~/mydir/notes_html/',
            \ 'diary_rel_path': 'дневник/',
            \ 'diary_index': 'дневник',
            \ 'diary_header': 'Дневник',
            \ 'auto_diary_index': 1,
            \ 'auto_tags': 1,
            \ 'syntax': 'markdown', 
            \ 'custom_wiki2html': '~/mydir/notes/bin/wiki2html.sh',
            \ 'template_path': '~/mydir/notes/bin/',
            \ 'template_default': 'GitHub.html5',
            \ 'links_space_char': '_',
            \ 'ext': '.md' }]

au FileType vimwiki set syntax=markdown
au FileType vimwiki set foldlevel=3

" In ftplugin/vimwiki.vim:

colorscheme onehalfdark

CocDisable

set laststatus=0
set foldcolumn=4

au! BufWritePost ~/mydir/notes/* !git add "%";git commit -m "Auto commit of %:t." "%"
```

-  `:VimwikiShowVersion`.
```

Os: Linux
Vim: 800
Branch: dev

Revision: dc2b16a

Date: 2020-10-24 19:43:01 -0300
```
- `:echo $LANG` prints `ru_RU.UTF-8`

**Comment by tinmarino** [comment] 2023-06-26 23:02
Closing <= stagnant and cannot reproduce

**Closed by tinmarino** 2023-06-26 23:02 UTC
