### ISSUE TITLE
spell check

### ISSUE THREAD

**Issue by rwmitchell** [vimwiki/vimwiki#1276] opened 2022-10-20 12:43 UTC
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.
       Stable version: 2.5

How can spell check be enabled for all lines?  What I'm seeing are only lines beginning with # show misspelled words.

<img width="121" alt="image" src="https://user-images.githubusercontent.com/15944841/196950742-a7f3477d-3c9f-4d07-a2ec-f551cac5567f.png">

I only start lines with # for header levels, none of they body shows misspelled lines.  Am I missing a setting?
Thanks!

**Comment by brennen** [comment] 2023-03-04 20:59
I'm unable to reproduce this, and it feels sort of unlikely to be specific to VimWiki. What version of Vim are you on?

**Comment by tinmarino** [comment] 2023-03-17 03:15
I am also unable to reproduce: spellcheck works fine for me with vimwiki.

```vim
set spell
set spelllang=en
hi SpellBad ctermfg=red
```

![Screenshot from 2023-03-17 00-14-06](https://user-images.githubusercontent.com/6123962/225803570-f4a37b1a-a2ec-418e-94c1-186823615920.png)

**Comment by tinmarino** [comment] 2023-03-17 03:18
Closing. Please open another issue when:

1. Use wimviki  dev branch
2. Paste the output of `VimwikiShowVersion`
3. Use the minimal possible vimrc (loading only vimwiki)

The error is probably a package conflict. You can then detect the conflicts by dichotomy. First of all, uncomment the packadd vimwiki in your vimrc or remove vimwiki from the automatic packages load to see if Vimwiki is involved.

**Closed by tinmarino** 2023-03-17 03:18 UTC
