### ISSUE TITLE
Vimwiki is unable to generate HTML for files with names that contain non-ASCII characters

### ISSUE THREAD

**Issue by TheSilvus** [vimwiki/vimwiki#615] opened 2019-02-19 10:33 UTC
Creating a file called e.g. `Universität.wiki` and attempting to convert it to HTML using any command causes it to fail because it is unable to open the file.

**Comment by hq6** [comment] 2019-03-22 17:45
@TheSilvus , I cannot reproduce this on `master` or on `dev`. That is, the HTML generates fine for me even if the file has the name you gave. I used the command Vimwiki2HTML.

Can you give more details about what you are doing to produce this error?

**Comment by hq6** [comment] 2019-03-28 21:54
In the absence of a response, I am closing this Issue for repo sanitation.
Please feel free to reopen or create a new issue if someone is able to reproduce this.

**Closed by hq6** 2019-03-28 21:54 UTC
Labels: need-more-info
