### ISSUE TITLE
Cannot return to page with `#` character in title.

### ISSUE THREAD

**Issue by dotancohen** [vimwiki/vimwiki#130] opened 2015-04-20 10:08 UTC
When pressing `Backspace` to return to a page with the `#` character in the title, this is the error that VIM throws:

```
Error detected while processing function vimwiki#base#go_back_link:                                                          
line    4:
E194: No alternate file name to substitute for '#': :e /home/dotancohen/.vimwiki/vmc/Foo\ #4252\ 
permissions.wiki
```

**Comment by dotancohen** [comment] 2015-04-20 10:08
Possibly related issue:
https://github.com/vimwiki/vimwiki/issues/25

**Comment by EinfachToll** [comment] 2015-04-24 14:14
The problem is more that we didn't really define which characters are allowed in a page name. Since `#` is the character used to separate file name from anchor in a link, it probably shouldn't be used in a page name. I'm surprised that this is the only problem you run into :)
Closing this, because it's more or less a duplicate of #88.

**Closed by EinfachToll** 2015-04-24 14:14 UTC
