### ISSUE TITLE
Proposal for Markdown as Default markup for Vimwiki files

### ISSUE THREAD

**Issue by Harsh-Vardhan** [vimwiki/vimwiki#15] opened 2013-09-12 12:41 UTC
Please don't get me wrong, I have learned the Vimwiki markup and it is burnt on my fingers so much that I find myself organizing my normal text files with it. However when I made a new wiki purposed to act as my blog I decided to go with the markdown syntax.

I resorted to markdown mainly because I wanted more features from the default **converter to HTML** in Vimwiki and have started learning it. **Markdown** has gathered much support as the writing system for the web. In addition parsers and converters to HTML for the **markdown** syntax are more mature and are being developed collaboratively by many.

If we stick with the custom markup originally developed for Vimwiki we will lose out on the collective intelligence of programmers working on markdown. By adopting a well-known and well-supported writing standard as default for Vimwiki I can see many benefits
- no documentation or support required for our original markup
- reduced barrier to entry for new users
- better support for parsers and converters to HTML
- one less feature to maintain and support

I hope you'd consider my proposal.

**Comment by a-b** [comment] 2015-01-27 23:25
It would be great to have github markdown https://guides.github.com/features/mastering-markdown/

it might be an amazing feature to publish diary or page as gist using gist plugin

**Comment by EinfachToll** [comment] 2015-02-03 13:28
@a-b I don't know if I get you right, but alternative syntaxes (e.g. markdown and media wiki) are already supported (see `:h vimwiki-option-syntax`), it's just that markdown support is still incomplete (e.g. links)

**Comment by blessedbiped** [comment] 2015-03-24 22:59
I think perhaps part of the problem is that it's not quite clear how to enable markdown syntax. Just got done reading the help file and I'm still stumped on how to make it happen. Should I just paste the example text into my vimrc, or is there another configuration file somewhere that I'm missing?

**Comment by blessedbiped** [comment] 2015-03-24 23:28
Figured it out, for anyone else looking for this option you **do** need to put the example text in your vimrc.

**Comment by EinfachToll** [comment] 2015-03-25 08:21
@blessedbiped: Don't know if I get you right, but to change the syntax of a wiki, all you have to do is to set the value of the 'syntax' key in g:vimwiki_list to 'markdown' or whatever.

**Comment by blessedbiped** [comment] 2015-03-25 13:16
Exactly my point. While I could understand that there is an option somewhere, the phrase, ```"set the value of the syntax key in g:vimwiki_list"``` means nothing to the average user (me). It took me blindly copying and pasting things from the help file into my vimrc to discover how this option is set.

**Comment by a-b** [comment] 2015-04-02 05:26
Is it possible to use ```vimwiki-todo-lists``` with markdown syntax?
Or something compatible with GitHub markdown todo list?

**Comment by EinfachToll** [comment] 2015-04-02 07:06
Do you just ask or did you try it out and it doesn't work? Normally, it should work for markdown syntax as well.

**Comment by linuxcaffe** [comment] 2015-04-02 08:09
@EinfachToll , @a-b 
FYI
New and exciting plugin on the scene, enhancing vimwiki with taskwarrior tasks (replaces vimwiki todos)
https://github.com/tbabej/taskwiki

**Comment by MBuchaus** [comment] 2016-05-13 13:02
There is https://tools.ietf.org/html/rfc7763

**Comment by digdig** [comment] 2016-09-18 03:52
I also highly recommend using markdown as default. This would attract a lot of new users. I think everyone knows markdown but only a few know the syntax of vimwiki. The default syntax of stackexhange and github using markdown must have a reason. You can't forget the syntax if you are using it everyday, and jump between the two syntax can have pain in some sense.

**Comment by tnguyen14** [comment] 2016-12-13 19:50
Any chance this could be considered at a higher priority?

I'd like to add a voice to supporting Markdown by default. It would make it a bit friendlier and more appealing. Then if there are special features that vimwiki syntax can offer better, those can definitely be highlighted.

The benefits of MD is that it would be more portable, so the notes can be used with other softwares if needed/ desired.

**Comment by linuxcaffe** [comment] 2016-12-14 03:11
+1 for markdown default. As much as I personally prefer the default syntax, the ubiquity of markdown is a strong argument.

**Comment by sheluchin** [comment] 2016-12-15 18:01
+1

Found Vimwiki through a recent HN post, and I agree with the sentiment here. Being able to dive right in and use the syntax most people are already familiar with would help to reduce the learning curve and increase adoption.

**Comment by enpassant** [comment] 2016-12-16 23:58
With this **custom_wiki2html** bash script and **pandoc** program, you can convert markdown to html:
```bash
#!/bin/bash

FORCE="$1"
SYNTAX="$2"
EXTENSION="$3"
OUTPUTDIR="$4"
INPUT="$5"
CSSFILE="$6"

FILE=$(basename "$INPUT")
FILENAME=$(basename "$INPUT" .$EXTENSION)
FILEPATH=${INPUT%$FILE}
OUTDIR=${OUTPUTDIR%$FILEPATH*}
OUTPUT="$OUTDIR"/$FILENAME
# >&2 echo "$FILEPATH $INPUT $FILENAME $OUTDIR $OUTPUT"

pandoc -s "$INPUT" -t html -o "$OUTPUT"
```
Html file name will be exactly the same as the markdown link. E.g:
Markown link sample:
\[Link descript\](link_name)
Markdown file name: link_name.md
Html file: link_name

**Comment by dotancohen** [comment] 2016-12-19 13:25
@enpassant I currenlty use `grip` to convert to HTML, it supports Github-flavoured markdown:
https://github.com/joeyespo/grip

Actually, `grip` sends the files off to Github itself for rendering, which may be an advantage or disadvantage in different situations.

**Comment by derrickcope** [comment] 2017-06-06 22:19
Just started using vimwiki. It's great, but it would be greater if it had full support for markdown.

**Comment by derrickcope** [comment] 2018-05-16 06:28
Github and Reddit use markdown. Has there been any progress on this issue?

**Comment by ranebrown** [comment] 2019-03-30 00:31
@EinfachToll @Nudin @hq6 Is there any interest in making Markdown the default syntax in a v3.0 release? The CommonMark spec is fairly well developed at this point and has been adopted by GitHub (with extensions). I would personally be in favor of this since it is the syntax that I use. If this isn't something that is going to happen I think we should close this instead of leaving it dangling as a possibility.

**Comment by hq6** [comment] 2019-03-30 07:27
@ranebrown, My only personal concern with changing the default is that there's no officially supported way (that I am aware of) to automatic convert between syntaxes. This is a concern because I suspect some people will want to move to Markdown after the switch, because they will (likely rightfully) believe that the default syntax will be better supported than non-default syntaxes just by virtue of being default. Since this project has existed for a few years, there's probably a ton of legacy wikis in the current default syntax. 

Additionally, I suspect only @EinfachToll  or @Nudin has the requisite knowledge to answer the following questions, which I believe it would be useful to have answers to before a switch.

1. Are there a substantial set of features (which people care about) that work only in the current default syntax? (`Vimwiki2HTML` to is the only thing that comes to mind currently)
2. How far are we from Markdown support that is at least a consistent subset of CommonMark?

Finally, by virtue of repository ownership (and official hand-off from the creator), I think @EinfachToll has the final say on a change as substantial as this, so we should get his opinion before moving on this.

**Comment by hq6** [comment] 2019-03-30 08:43
After a little more reflection on this, I vote in favor of closing this issue for the time being, because I do not think the benefits (one fewer line of `.vimrc` for people using Markdown syntax) outweighs the risks.
 
 * One risk that comes to mind is that Vimwiki's documentation assumes the current default syntax. If we were to change the default syntax, there would be a large degree of confusion for new users unless we very carefully updated the documentation. I think pointing people to the Markdown spec will be neither here nor there, since we don't quite implement everything in it, and we also layer other extensions on top (such as Tables and Tasks).
 * Another risk is our functionality conflicting with [plugins for Markdown](https://github.com/plasticboy/vim-markdown) if both try to activate on files with the `.md` extension. Again, this is highly fixable but the concern is that users new to Vimwiki will have an unfortunate out-of-the-box experience.

**Comment by Nudin** [comment] 2019-04-08 13:25
I'm not in favor for swiching the default. I think markup languages are mostly a matter of taste and accustomization and there have been changes before in what "the cool kids use". ;) So I don't see a intrinsic benefit of any syntax over any other.

I don't see a stategy for how to deal with all the wikis out there using default-syntax (without explicit configuration) – they would break when we change the default. I also see the problems mentioned by @hq6 and I don't see much of benefits from changing the default syntax – in the end most comments on this issue are less about the default syntax but about missing features when using the mardown syntax. And the fact that markdown is supported less well is that the developers who worked on vimwiki in the past all used default-syntax – keep in mind that this is a free-time-project by a very small amount of people. It already got better since we have more active maintainers now!

Therefore I would argue to stay with vimwiki as the default setting and close this issue, but:

- [ ] Consider to make it easier to swich to markdown syntax.
- [ ] Improve documentation – already started by #572
- [ ] Create a project to track progress on feature-parity
- [ ] Create a project to track progress on compability to CommonMark

The best way to increase progress in these topics in to help vimwiki, see #625!

**Comment by ranebrown** [comment] 2019-04-09 12:29
See #664 for the status of Markdown improvements.

**Closed as completed by ranebrown** 2019-04-09 12:29 UTC
Labels: enhancement, pending-closure
