### ISSUE TITLE
VimWiki doesn't know what to do with links to directories

### ISSUE THREAD

**Issue by zyl-hub** [vimwiki/vimwiki#996] opened 2020-08-24 13:00 UTC
I have tried out vimwiki. It's pretty nice for me. 
## Problem
I create a link to a folder and I open the folder in vimwiki. There were some thing error in filetype. The filetype should be netrw. But filetype was detected as vimwiki. Then the files under the folder cannot be opened correctly.

**Comment by tinmarino** [comment] 2020-09-04 04:13
Hi @zyl-hub vimwiki is only opening files. This is almost a bug, so I'll pu this issue in bug triage.
Meanwhile, as far a I know open the directory with a system command, in markdown:
```makrdown
[dir1](file:dir1/)
```
the problem is that you are leaving vim

**Comment by brennen** [comment] 2022-05-22 17:47
As a workaround, you can write a link handler like so:

```vim
    " override default vimwiki link handling - could be extended to add
    " custom link types, etc.  Right now all it does is use vim itself
    " to handle files, crudely.
    function! VimwikiLinkHandler(link)
      if a:link =~# '^file:'
        try
          " chop off the leading file: - see :h expr-[:] for syntax:
          execute ':split ' . a:link[5:]
          return 1
        catch
          echo "Failed opening file in vim."
        endtry
      endif
      return 0
    endfunction
```

**Comment by tinmarino** [comment] 2023-06-26 23:35
Closing <= if feature is desired, please use @brennen work around above

**Closed by tinmarino** 2023-06-26 23:35 UTC
Labels: enhancement, work-around-exists, link
