### ISSUE TITLE
Inline code highlighting does not work with markdown syntax

### ISSUE THREAD

**Issue by BonarBeavis** [vimwiki/vimwiki#244] opened 2016-09-22 08:50 UTC
Hi,

code is just red instead of highlighted. The markup won't disappear either. 
It works after sourcing .vimrc. But then filetype is markdown and not vimwiki.

Cheers

**Comment by EinfachToll** [comment] 2016-11-23 20:53
I merged jconroy77's PR, so it should work now!

**Closed by EinfachToll** 2016-11-23 20:53 UTC

**Comment by MatthiasKauer** [comment] 2016-11-27 08:55
Hey, I'm very new to vimwiki and I'm not sure whether there are still problems with this or whether I'm seeing expected behavior.

In a markdown file, I write.
```
Some inline code ```return true``` or with a pointer ```int func(T*) {return 0;}```.
```
Once my cursor leaves the line, it is displayed to me as:
```
Some inline code ``return true` or with a pointer `int func(T*) {return 0;}`.
```
Markdown links also seem to have this show/hide behavior, so this may be intentional. Is it?
In addition, all code blocks including the text in-between is marked in red.

**Comment by EinfachToll** [comment] 2016-11-27 21:00
AFAIK, the way you formatted the inline code is indeed valid markdown, but it's not really supported by Vimwiki, because Vim can't properly highlight it using regexes. For inline code, use single backtics:
```
Some inline code `return true`.
```
And for code blocks, use 3 backtics:
~~~
```
int func() {
  return 2;
}
```
~~~

**Comment by MatthiasKauer** [comment] 2016-11-28 20:37
@EinfachToll : Interesting. It turns out that me using three backticks was a total misunderstanding on my part.
I have also found in the meantime that I can turn of concealing and URL shortening as well (conceallevel and url_maxsave if anyone is wondering).

This tool is looking more and more promising to me :) Thank you!
