### ISSUE TITLE
Cannot unbind <leader>wi

### ISSUE THREAD

**Issue by worldpe** [vimwiki/vimwiki#1165] opened 2021-08-25 20:19 UTC
When I attempt to unbind the command, I am told that it does not exist, but it appears to be the case that it does exist as it is 100% replicable.

**Comment by brennen** [comment] 2021-08-28 19:21
I'm unable to reproduce this - running `:unmap <Leader>wi` behaves as expected.

Please post Vim version, output of `:VimwikiShowVersion`, configuration from your `.vimrc`, and exactly what command you're running and the error message given.

**Comment by tinmarino** [comment] 2023-06-14 18:21
Closing <= cannot reproduce either

**Closed by tinmarino** 2023-06-14 18:21 UTC
Labels: config, map
