### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by lifranc** [vimwiki/vimwiki#569] opened 2018-10-02 05:09 UTC
Tried dev branch, master branch, added the options in the install instructions, and still get this error. On nixOS, so there are no 'files left over' as it is all done declaratively.
```
Error detected while processing function vimwiki#base#goto_index[30]..vimwiki#base#edit_file:
line   23:
E325: ATTENTION
```

I am no neovim wizard, and don't yet know how to get a longer log. I'd be happy to follow anyone's instructions to debug this.

**Comment by bluddy** [comment] 2018-10-10 18:43
Long time user here. I'm constantly getting errors as well.

I also get errors when entering a wiki page, and it seems to do with existing swap files being found, which for some reason is always the case. It appears like the vimwiki code doesn't recover well from the swap file found error -- backspace doesn't take me back up, for example. Going back to the main page and reloading the specific wiki page fixes things, because the second time, the swap files aren't there.

**Comment by evantravers** [comment] 2018-10-15 20:02
Yeah… I'm getting weird errors… I think it does have to do with swap files as well. It just hangs and then if I hit enter, I'll get an error message and then a Read-Only buffer.

**Comment by EinfachToll** [comment] 2018-10-15 20:04
So does the error happen to you every time you open a Vimwiki page? Also if you have a "clean" file system (that is, without old swap files lying around)?

**Comment by evantravers** [comment] 2018-10-15 20:37
It was happening every time… I am playing with it now… I think what is happening is that I have this block of config in my vimrc:

```
" Backup Directories
set backupdir=~/.config/nvim/backups,.
set directory=~/.config/nvim/swaps,.
if exists('&undodir')
  set undodir=~/.config/nvim/undo,.
endif
```

but I didn't have the folders created… I'm on a new computer. Now that I've created the folders, it seems to be behaving better.

**Comment by EinfachToll** [comment] 2018-10-16 20:18
Ok, I can see the same error message as @lifranc when I open one wiki file in two instances of Vim and then press escape a number of times. The error handling can certainly improved on Vimwiki's side, but the cause of the error has nothing to do with Vimwiki, so we can't fix it.
But I wonder if this is the same problem as you guys have.

**Comment by ranebrown** [comment] 2019-03-21 03:15
It looks like this might have been resolved in the latest `dev` branch. @lifranc, @bluddy, @evantravers can any of you confirm if there is still an issue?

**Comment by evantravers** [comment] 2019-03-21 21:33
@ranebrown I have not been able to replicate the bug on `dev`… but I honestly haven't seen it for a while on `master` either… I can't tell if that's because I'm being more careful with my habits or what.

**Comment by jpittis** [comment] 2019-03-21 21:35
I've just confirmed that this is fixed on the latest `dev` branch but not on `master`.

**Comment by ranebrown** [comment] 2019-03-21 22:16
Thanks for the update. I'm going to close this since it has been fixed. We are in the process of releasing a new version that will be available on `master` within the next couple of weeks. Feel free to reopen if anything comes up.

**Closed by ranebrown** 2019-03-21 22:16 UTC
Labels: bug, need-more-info
