### ISSUE TITLE
escape seems to close vim splits and tabs

### ISSUE THREAD

**Issue by michael-odonovan** [vimwiki/vimwiki#1312] opened 2023-03-13 10:25 UTC
Hello,
Thanks for the plugin! : )
Having an issue today where any extra windows / splits are closed whenever I hit escape.
So `:vsp` and then hitting escape immediately closes the split. This make using vim to edit the new split quite difficult : )

Prior to submitting a new issue make sure to complete these steps:

- [ x ] Include the VimWiki settings from your `.vimrc`
```
-- vimwiki plugin =================
vim.g.vimwiki_list = {
  {
    path = '~/Repos/Wiki',
    syntax = 'markdown',
    ext = '.md',
  },
}
vim.g.vimwiki_ext2syntax = {
  ['.md'] = 'markdown',
  ['.markdown'] = 'markdown',
  ['.mdown'] = 'markdown',
}
vim.g.vimwiki_global_ext = 0 -- don't treat all md files as vimwiki (0)
vim.g.vimwiki_hl_headers = 1 -- use alternating colours for different heading levels
vim.g.vimwiki_markdown_link_ext = 1 -- add markdown file extension when generating links
vim.g.taskwiki_markdown_syntax = "markdown"

vim.cmd([[
  hi VimwikiHeader1 guifg=#c94f6d
  hi VimwikiHeader2 guifg=#ffff00
  hi VimwikiHeader3 guifg=#7AF8FF
  hi VimwikiHeader4 guifg=#f4a261
  hi VimwikiHeader5 guifg=#d67ad2
  hi VimwikiLink guifg=#719cd6 gui=underline
  hi VimwikiListTodo guifg=#81b29a
]])
```

- [ x ] Include the syntax you are using (default / Markdown / MediaWiki) 
markdown
- [ x ] Provide a detailed description of the problem including **steps to reproduce the issue**.

- [ x ] Include the output of `:VimwikiShowVersion`.

Version: 2022.12.02
Os: Mac
Vim: 801
Branch: dev
Revision: 34ceee8
Date: 2023-03-12 01:48:31 -0300

**Comment by tinmarino** [comment] 2023-03-13 15:40
Hello @michael-odonovan,

Thank you for using vimwiki. This is a weird bug. Can you please:

1. paste the output of `map <esc>`. Note that the `alt` modifier is the same as pressing escape then the key
2. attach of paste your full vimrc to see if there is a bad map or autocommand or hopefully reproduce the bug.

Cheers,
Martin.

**Comment by michael-odonovan** [comment] 2023-03-13 16:10
Hey Martin,
thanks so much for getting back to me.

`:map <esc>`
gives:
`No mapping found`

My vim repo is public:
https://github.com/michael-odonovan/nvim-packer

**Comment by tinmarino** [comment] 2023-03-13 16:44
Thank you @michael-odonovan,

Can you please test again with a minimal vimrc (only importing vimwiki), and it case it works,  find the conflicting pluggin by dichotomy?

This seems like a plugin conflict

**Comment by tinmarino** [comment] 2023-06-22 21:36
Hello @michael-odonovan, I cannot reproduce, have you found a solution? I cannot your configuration (private).

**Comment by tinmarino** [comment] 2023-06-23 13:50
Closing <= cant reproduce

**Closed** 2023-06-23 13:50 UTC
Labels: question, need-more-info
