### ISSUE TITLE
Feature Request: Support GFM anchor links inside wiki files

### ISSUE THREAD

**Issue by bratekarate** [vimwiki/vimwiki#831] opened 2020-03-12 15:16 UTC
Prior to submitting a new issue make sure to complete these steps:

- [x] Checkout the `dev` branch and confirm the issue is present there as well.
      The `dev` branch contains fixes that may not have been merged to `master` yet.
- [x] Post the syntax you are using (default/mediawiki/markdown) **and** your vimwiki settings from your `.vimrc`
- [x] Provide a detailed description of the problem including **steps to reproduce the issue**.
- [x] Include the output of `:VimwikiShowVersion`.

- Syntax used: markdown
## Description
Links to Headers/Anchors require as url the exact same text as the header that is linked to. Otherwise they don't work. Example:
```
[Link to heading](#Heading Example)
## Heading Example
```
For HTML export, e.g. with pandoc, or when using the same wiki content for an engine that uses GFM, it is desirable to use hyphens instead of spaces in the link url and use only lowercase. For a table of contents that is usable after HTML export, plugins like [mzlogin/vim-markdown-toc](https://github.com/mzlogin/vim-markdown-toc) can be used. Example:
```
[Link to heading](#heading-example)
## Heading Example
```
This works great for export, but inside vim the links are not usable. It would be great if vimwiki would also recognize these links, for instance by first trying the exact name and afterwards with lowercase and hyphens.

**Comment by ranebrown** [comment] 2020-03-23 11:56
This is something I've been wanting to fix as well, just haven't had the time. If you want to open a PR that would be great.

**Comment by bratekarate** [comment] 2020-03-24 00:07
If I find the time I may be able to. Haven't checked out the responsible code yet though and don't know how complex this change would be.

**Comment by bratekarate** [comment] 2020-03-25 02:29
Done, #840. Not sure if that's the way to go, but it works. Tell me if it should be improved, don't know if I find any more time soon. 

Also (although unrelated), #828 is still open and ready to merge.

**Comment by bratekarate** [comment] 2020-03-31 13:32
@ranebrown have you checked out my PR yet?

**Comment by ranebrown** [comment] 2020-04-02 10:26
This is actually a duplicate of #666. [This comment](https://github.com/vimwiki/vimwiki/issues/666#issuecomment-570753457) has some useful info.

**Comment by tinmarino** [comment] 2020-07-30 04:05
Close with PR #840 in favor of Issue #666 trakcing the remaining support

**Closed by tinmarino** 2020-07-30 04:05 UTC
Labels: enhancement, markdown

**Comment by folofjc** [comment] 2022-07-11 11:21
Has this been pushed to `master`? This functionality doesn't appear to work for me and I cannot find it in the commit history of `master`.
