### ISSUE TITLE
Only links on titles are being contracted

### ISSUE THREAD

**Issue by AnderRasoVazquez** [vimwiki/vimwiki#210] opened 2016-05-25 00:27 UTC
Check out last line.
![vimwiki1](https://cloud.githubusercontent.com/assets/3936719/15524141/f34be70a-221f-11e6-8ad7-77397b553c8d.png)
![2 _130](https://cloud.githubusercontent.com/assets/3936719/15524144/f5d59a02-221f-11e6-83a7-e013c57639e7.png)

As you can see my other links are not being contracted, any idea why?

**Comment by EinfachToll** [comment] 2016-05-25 14:03
Well, the last line in the TOC (line 9) is screwed up because of the multiple `[` and `]`. That's a bug.
I'm not sure about the other links. Does something interesting happen if you just remove line 9? Can you post your Vimwiki related settings?

**Comment by AnderRasoVazquez** [comment] 2016-05-25 18:27
**Vimwiki related settings**:
```
let wiki = {}
let wiki.path = '~/vimwiki/'
let wiki.nested_syntaxes = {'python': 'python', 'c++': 'cpp'}
let g:vimwiki_list = [wiki]
let g:vimwiki_diary_months = {
      \ 1: 'Enero', 2: 'Febrero', 3: 'Marzo',
      \ 4: 'Abril', 5: 'Mayo', 6: 'Junio',
      \ 7: 'Julio', 8: 'Agosto', 9: 'Septiembre',
      \ 10: 'Octubre', 11: 'Noviembre', 12: 'Diciembre'
      \ }
let g:vimwiki_list = [{'path': '~/vimwiki/', 'auto_toc': 1}]
let g:vimwiki_folding='syntax'
```
It doesn't happen anything when I remove line 9.
Thanks for answering so quickly =)

**Comment by AnderRasoVazquez** [comment] 2016-05-25 18:36
Ok I found the error. [Plugin luochen1990/rainbow](https://github.com/luochen1990/rainbow) conflicts with vimwiki. I deactivated it and links contract perfectly. **TOC bug still is there**.
![seleccion_131](https://cloud.githubusercontent.com/assets/3936719/15551853/230441de-22b8-11e6-8d05-c8db5db16a49.png)

**Comment by Nudin** [comment] 2018-12-19 21:58
Closing as duplicate of #210

**Closed by Nudin** 2018-12-19 21:58 UTC
