### ISSUE TITLE
Breaks when used with auto-pairs plugin

### ISSUE THREAD

**Issue by Coleej** [vimwiki/vimwiki#356] opened 2017-06-07 01:50 UTC
I recently installed [auto-pairs](https://github.com/jiangmiao/auto-pairs). When I perform basic editing operations in a .vimwiki buffer, I get the following text inserted instead of the action:

\<SNR\>20_AutoPairsReturn

The action could be pressing <CR> while in insert mode. This behavior didn't always occur and I could use both plugins for a while.

**Comment by Nudin** [comment] 2017-10-25 15:29
I've installed auto-pairs now – so far haven't been able to reproduce. Any further info, about how to reproduce this behavior?

**Comment by johnmarcampbell** [comment] 2017-11-02 18:15
Closing this, due to going ~8 days without additional info. We can reopen this issue if more info is provided.

**Closed by johnmarcampbell** 2017-11-02 18:15 UTC
Labels: bug, need-more-info
