### ISSUE TITLE
markdown_base#normalize_link_syntax_v cannot handle apostrophe

### ISSUE THREAD

**Issue by silvioricardoc** [vimwiki/vimwiki#436] opened 2018-02-06 20:49 UTC
# Context
The function `markdown_base#normalize_link_syntax_v` contains the following lines:
```vim
let link = substitute(g:vimwiki_Weblink1Template, '__LinkUrl__', '\='."'".visual_selection."'", '')
let link = substitute(link, '__LinkDescription__', '\='."'".visual_selection."'", '')
```
In this code, the variable `visual_selection` is not escaped, which causes problems if we try to create a link for a text containing an apostrophe. I'm wondering why the `\=` technique was deemed necessary. Shouldn't the following code be enough?

```vim
let link = substitute(g:vimwiki_Weblink1Template, '__LinkUrl__', visual_selection, '')
let link = substitute(link, '__LinkDescription__', visual_selection, '')
```

**Comment by ranebrown** [comment] 2019-07-18 11:36
I think this is a duplicate of #88 which has been fixed. Please reopen if you are still seeing the issue.

**Closed by ranebrown** 2019-07-18 11:36 UTC
Labels: duplicate
