### ISSUE TITLE
Saving diary entry hiding calendar and showing again breaks the calendar's ability to navigate to proper date files

### ISSUE THREAD

**Issue by jondkinney** [vimwiki/vimwiki#219] opened 2016-06-17 06:09 UTC
Hi there,

Thanks for vimwiki! I'm really enjoying the calendar plugin to manage diary entries. However, if open the wiki, open the calendar, save an entry (today's or any time), hide the calendar, then show the calendar again, it tries to open pages with the plusses in between the days... I'll try to show:

![image](https://cloud.githubusercontent.com/assets/4521/16142074/05ec5600-3428-11e6-807d-7883f6f0b0ed.png)

I dug through the source a bit, but I was unable to track it down. It's a bit over my head, currently.

Thanks!

**Comment by EinfachToll** [comment] 2016-06-17 18:55
> then show the calendar again, it tries to open pages with the plusses in between the days

So Vimwiki opens this strange file as soon as you open the calendar again? Or when you press enter in the calendar? If the latter, where is the cursor when you press enter?
BTW, this looks more like an issue of calendar.vim. Do you use the newest version of it?

**Comment by jondkinney** [comment] 2016-06-17 18:59
@EinfachToll it opens the strangely named file when pressing enter. I've tried my cursor on the day number itself (or on either digit if there are two) and on the plus as well. The problem, it seems, is that after the calendar is re-shown, it doesn't initialize properly (or something) and it treats any string of multiple days where previously there were individual entries as one text object with plusses between the dates. 

I have the latest version of calendar.vim, I just installed it yesterday for the first time.

Thanks for taking a look!

**Comment by EinfachToll** [comment] 2016-06-17 20:22
I can't reproduce the issue, and have no real clue. I can only give you a hint where to look for the cause. If you put a line like this in `your_vim_installation/bundle/calendar-vim/autoload/calendar.vim`, line 215, so that 

```viml
  " call the action function
  exe "call " . g:calendar_action . "(day, month, year, week, dir)"
```

becomes

```viml
  " call the action function
  echom day month year week dir
  exe "call " . g:calendar_action . "(day, month, year, week, dir)"
```
then you can, after you opened the calendar and pressed enter on some date, type `:messages` and see the debug output. Normally, it should look like `vimwiki#diary#calendar_action 14 6 2016 1 V`. If it's something else, then probably calendar.vim messes things up.

**Comment by hq6** [comment] 2019-04-02 16:39
Closing this issue since it does not appear to be reproducible and no further comment from OP. 

Please feel free to reopen with more concrete steps for reproducing the issue.

**Closed by hq6** 2019-04-02 16:39 UTC
